import AdminFormField from '@/Components/common/AdminFormField';
import AutoGeneratedCodeField from '@/Components/common/AutoGeneratedCodeField';
import DataTable from '@/Components/common/DataTable';
import PageHeader from '@/Components/common/PageHeader';
import ImportExportToolbar from '@/Components/import-export/ImportExportToolbar';
import { useImportJobsTray } from '@/Components/import-export/ImportJobsTray';
import Modal from '@/Components/Modal';
import { Button } from '@/Components/ui/button';
import Select from '@/Components/ui/select';
import { withAdminLayout } from '@/HOCs/withAdminLayout';
import { useCan } from '@/Hooks/useCan';
import { Head, router, useForm } from '@inertiajs/react';
import { Briefcase, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

function emptyForm(legalEntities = [], nextCode = '') {
    return {
        legal_entity_id: legalEntities[0] ? String(legalEntities[0].id) : '',
        code: nextCode ?? '',
        name: '',
        default_grade_id: '',
        status: 'active',
    };
}

function Index({ designations, filters, legalEntities = [], grades = [], nextCode = '' }) {
    const can = useCan();
    const { t } = useTranslation();
    const { trackJob } = useImportJobsTray();
    const [modalOpen, setModalOpen] = useState(false);
    const [editing, setEditing] = useState(null);
    const form = useForm(emptyForm(legalEntities, nextCode));

    const statusOptions = useMemo(
        () => [
            { value: '', label: t('common.allStatuses') },
            { value: 'active', label: t('pages.hrDesignations.statuses.active') },
            { value: 'inactive', label: t('pages.hrDesignations.statuses.inactive') },
        ],
        [t],
    );

    const entityOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrEmployees.selectLegalEntity') },
            ...legalEntities.map((e) => ({ value: String(e.id), label: e.legal_name })),
        ],
        [legalEntities, t],
    );

    const gradeOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrDesignations.fields.noDefaultGrade') },
            ...grades.map((g) => ({ value: String(g.id), label: `${g.code} — ${g.name}` })),
        ],
        [grades, t],
    );

    const formStatusOptions = useMemo(
        () => [
            { value: 'active', label: t('pages.hrDesignations.statuses.active') },
            { value: 'inactive', label: t('pages.hrDesignations.statuses.inactive') },
        ],
        [t],
    );

    const openCreate = () => {
        setEditing(null);
        form.clearErrors();
        form.setData(emptyForm(legalEntities, nextCode));
        setModalOpen(true);
    };

    const openEdit = (row) => {
        setEditing(row);
        form.clearErrors();
        form.setData({
            legal_entity_id: row.legal_entity_id ? String(row.legal_entity_id) : '',
            code: row.code ?? '',
            name: row.name ?? '',
            default_grade_id: row.default_grade_id ? String(row.default_grade_id) : '',
            status: row.status ?? 'active',
        });
        setModalOpen(true);
    };

    const submit = (e) => {
        e.preventDefault();
        const options = {
            preserveScroll: true,
            onSuccess: () => setModalOpen(false),
            onFinish: () => form.transform((data) => data),
        };
        const payload = { ...form.data };
        delete payload.code;

        form.transform(() => payload);

        if (editing) {
            form.put(route('admin.hr.designations.update', editing.id), options);
        } else {
            form.post(route('admin.hr.designations.store'), options);
        }
    };

    const search = (e) => {
        e.preventDefault();
        router.get(route('admin.hr.designations.index'), Object.fromEntries(new FormData(e.target)), {
            preserveState: true,
        });
    };

    const columns = useMemo(
        () => [
            {
                id: 'name',
                header: t('pages.hrDesignations.columns.name'),
                cell: ({ row }) => (
                    <div className="flex items-center gap-3">
                        <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-sky-100 text-sky-600 dark:bg-sky-500/20 dark:text-sky-300">
                            <Briefcase className="h-4 w-4" />
                        </span>
                        <div>
                            <div className="text-sm font-semibold text-rp-text">{row.original.name}</div>
                            <div className="text-xs text-rp-text-muted">{row.original.code}</div>
                        </div>
                    </div>
                ),
            },
            {
                id: 'entity',
                header: t('pages.hrDesignations.columns.legalEntity'),
                cell: ({ row }) => row.original.legal_entity_name ?? '—',
            },
            {
                id: 'grade',
                header: t('pages.hrDesignations.columns.defaultGrade'),
                cell: ({ row }) => row.original.default_grade_name ?? '—',
            },
            {
                id: 'status',
                header: t('pages.hrDesignations.columns.status'),
                cell: ({ row }) =>
                    t(`pages.hrDesignations.statuses.${row.original.status}`, {
                        defaultValue: row.original.status,
                    }),
            },
        ],
        [t],
    );

    const rowActions = (row) => {
        if (!can('hr.manage-org')) {
            return [];
        }

        return [{ label: t('common.edit'), type: 'edit', onClick: () => openEdit(row) }];
    };

    return (
        <>
            <Head title={t('pages.hrDesignations.indexTitle')} />
            <PageHeader
                title={t('pages.hrDesignations.indexTitle')}
                description={t('pages.hrDesignations.indexDescription')}
            >
                <div className="flex flex-wrap items-center gap-2">
                    <ImportExportToolbar
                        entityType="designations"
                        entityLabel={t('pages.hrDesignations.indexTitle')}
                        exportOptions={{ filters: { search: filters.search ?? undefined, status: filters.status ?? undefined } }}
                        onJobStarted={trackJob}
                    />
                    {can('hr.manage-org') && (
                        <Button variant="brand" onClick={openCreate}>
                            <Plus className="h-4 w-4" />
                            {t('pages.hrDesignations.createTitle')}
                        </Button>
                    )}
                </div>
            </PageHeader>

            <form onSubmit={search} className="rp-filter-bar mb-4 flex-wrap gap-2">
                <div className="rp-search-inset min-w-[200px] flex-1">
                    <Search className="h-3.5 w-3.5 shrink-0 text-rp-text-muted" />
                    <input
                        name="search"
                        defaultValue={filters.search ?? ''}
                        placeholder={t('pages.hrDesignations.searchPlaceholder')}
                        className="rp-search-input"
                    />
                </div>
                <Select
                    name="status"
                    defaultValue={filters.status ?? ''}
                    className="w-auto min-w-[12rem]"
                    options={statusOptions}
                />
                <Button type="submit" variant="outline">
                    {t('common.search')}
                </Button>
            </form>

            <DataTable
                columns={columns}
                data={designations.data ?? []}
                pagination={designations}
                rowActions={rowActions}
                emptyMessage={t('pages.hrDesignations.empty')}
            />

            <Modal show={modalOpen} onClose={() => setModalOpen(false)} maxWidth="lg">
                <form onSubmit={submit} className="space-y-4 p-6">
                    <h3 className="text-lg font-semibold">
                        {editing
                            ? t('pages.hrDesignations.editTitle', { name: editing.name })
                            : t('pages.hrDesignations.createTitle')}
                    </h3>
                    <div className="grid gap-4 sm:grid-cols-2">
                        <AdminFormField
                            label={t('pages.hrEmployees.fields.legalEntity')}
                            id="legal_entity_id"
                            error={form.errors.legal_entity_id}
                        >
                            <Select
                                id="legal_entity_id"
                                value={form.data.legal_entity_id}
                                onChange={(value) => form.setData('legal_entity_id', value ?? '')}
                                options={entityOptions}
                            />
                        </AdminFormField>
                        <AutoGeneratedCodeField
                            label={t('pages.hrDesignations.fields.code')}
                            value={editing ? form.data.code : nextCode}
                            error={form.errors.code}
                            hint={editing ? undefined : t('pages.hrDesignations.fields.codeAutoHint')}
                        />
                        <AdminFormField label={t('pages.hrDesignations.fields.name')} id="name" error={form.errors.name}>
                            <input
                                id="name"
                                value={form.data.name}
                                onChange={(e) => form.setData('name', e.target.value)}
                                placeholder={t('pages.hrDesignations.fields.namePlaceholder')}
                                className="rp-form-input"
                                required
                            />
                        </AdminFormField>
                        <AdminFormField
                            label={t('pages.hrDesignations.fields.defaultGrade')}
                            id="default_grade_id"
                            error={form.errors.default_grade_id}
                        >
                            <Select
                                id="default_grade_id"
                                value={form.data.default_grade_id}
                                onChange={(value) => form.setData('default_grade_id', value ?? '')}
                                options={gradeOptions}
                                isClearable
                            />
                        </AdminFormField>
                        <AdminFormField label={t('common.status')} id="status" error={form.errors.status}>
                            <Select
                                id="status"
                                value={form.data.status}
                                onChange={(value) => form.setData('status', value ?? 'active')}
                                options={formStatusOptions}
                            />
                        </AdminFormField>
                    </div>
                    <div className="flex justify-end gap-2 pt-2">
                        <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>
                            {t('confirm.cancel')}
                        </Button>
                        <Button type="submit" variant="brand" disabled={form.processing}>
                            {editing ? t('common.save') : t('pages.hrDesignations.createSubmit')}
                        </Button>
                    </div>
                </form>
            </Modal>
        </>
    );
}

export default withAdminLayout(Index);
