<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Permission;
use App\Support\AccessControlLabels;
use Illuminate\Database\Seeder;

final class PermissionSeeder extends Seeder
{
    /**
     * @var array<string, list<array{name: string, description: string}>>
     */
    private const PERMISSIONS = [
        'admin' => [
            ['name' => 'admin.access', 'description' => 'Access the admin panel'],
            ['name' => 'admin.dashboard.view', 'description' => 'View admin dashboard (legacy alias)'],
        ],
        'dashboard' => [
            ['name' => 'dashboard.view', 'description' => 'View the ERP home dashboard'],
            ['name' => 'dashboard.view-profit', 'description' => 'View profit-sensitive dashboard figures'],
            ['name' => 'dashboard.sales.view', 'description' => 'View sales dashboard widgets'],
            ['name' => 'dashboard.inventory.view', 'description' => 'View inventory dashboard widgets'],
            ['name' => 'dashboard.finance.view', 'description' => 'View finance dashboard widgets'],
            ['name' => 'dashboard.procurement.view', 'description' => 'View procurement dashboard widgets'],
            ['name' => 'dashboard.operations.view', 'description' => 'View operations dashboard widgets'],
            ['name' => 'dashboard.exceptions.view', 'description' => 'View the business exception feed'],
        ],
        'users' => [
            ['name' => 'users.view', 'description' => 'View users'],
            ['name' => 'users.create', 'description' => 'Create users'],
            ['name' => 'users.update', 'description' => 'Update users'],
            ['name' => 'users.delete', 'description' => 'Delete users'],
            ['name' => 'users.assign-roles', 'description' => 'Assign roles to users'],
            ['name' => 'users.assign-branches', 'description' => 'Assign branches to users'],
        ],
        'roles' => [
            ['name' => 'roles.view', 'description' => 'View roles'],
            ['name' => 'roles.create', 'description' => 'Create roles'],
            ['name' => 'roles.update', 'description' => 'Update roles'],
            ['name' => 'roles.delete', 'description' => 'Delete roles'],
            ['name' => 'roles.clone', 'description' => 'Clone roles'],
            ['name' => 'roles.assign-permissions', 'description' => 'Assign permissions to roles'],
        ],
        'permissions' => [
            ['name' => 'permissions.view', 'description' => 'View permissions'],
            ['name' => 'permissions.create', 'description' => 'Create permissions'],
            ['name' => 'permissions.update', 'description' => 'Update permissions'],
            ['name' => 'permissions.delete', 'description' => 'Delete permissions'],
        ],
        'branches' => [
            ['name' => 'branches.view', 'description' => 'View branches'],
            ['name' => 'branches.create', 'description' => 'Create branches'],
            ['name' => 'branches.update', 'description' => 'Update branches'],
            ['name' => 'branches.delete', 'description' => 'Delete branches'],
            ['name' => 'branches.access-all', 'description' => 'Access all branches without assignment restrictions'],
        ],
        'warehouses' => [
            ['name' => 'warehouses.view', 'description' => 'View warehouses'],
            ['name' => 'warehouses.create', 'description' => 'Create warehouses'],
            ['name' => 'warehouses.update', 'description' => 'Update warehouses'],
            ['name' => 'warehouses.deactivate', 'description' => 'Deactivate warehouses'],
        ],
        'products' => [
            ['name' => 'products.view', 'description' => 'View products and catalog'],
            ['name' => 'products.create', 'description' => 'Create products'],
            ['name' => 'products.update', 'description' => 'Update products'],
            ['name' => 'products.delete', 'description' => 'Delete products'],
            ['name' => 'products.show-cost', 'description' => 'View cost price columns'],
            ['name' => 'products.import', 'description' => 'Import catalog data from spreadsheets'],
            ['name' => 'products.export', 'description' => 'Export catalog data to spreadsheets'],
        ],
        'inventory' => [
            ['name' => 'inventory.view', 'description' => 'View stock levels by warehouse'],
            ['name' => 'inventory.reports', 'description' => 'View and export stock reports'],
            ['name' => 'inventory.receive', 'description' => 'Receive stock into warehouse'],
            ['name' => 'inventory.adjust', 'description' => 'Adjust or write off stock'],
            ['name' => 'inventory.transfer', 'description' => 'Create and process stock transfers'],
            ['name' => 'inventory.import-opening-stock', 'description' => 'Import opening stock balances from spreadsheets'],
            ['name' => 'inventory.bulk-adjustment-import', 'description' => 'Bulk import stock adjustments from spreadsheets'],
            ['name' => 'inventory.manage-bins', 'description' => 'Manage warehouse zones and bin locations'],
            ['name' => 'inventory.release-quarantine', 'description' => 'Release or scrap quarantined stock'],
            ['name' => 'inventory.cycle-count', 'description' => 'Create and manage cycle count sessions'],
            ['name' => 'inventory.cycle-count.approve', 'description' => 'Approve cycle count variances'],
        ],
        'settings' => [
            ['name' => 'settings.view', 'description' => 'View global settings'],
            ['name' => 'settings.general.update', 'description' => 'Update general settings'],
            ['name' => 'settings.company.update', 'description' => 'Update company profile settings'],
            ['name' => 'settings.notifications.update', 'description' => 'Update notification settings'],
            ['name' => 'settings.file-storage.update', 'description' => 'Update shared file storage settings (images, attachments, import/export)'],
            ['name' => 'settings.tax.update', 'description' => 'Update tax calculation settings'],
            ['name' => 'settings.checkout.update', 'description' => 'Update checkout, payment, and invoice settings'],
            ['name' => 'settings.fbr.update', 'description' => 'Update FBR IRIS integration settings'],
            ['name' => 'settings.inventory.update', 'description' => 'Update inventory reservation and count settings'],
            ['name' => 'settings.procurement.update', 'description' => 'Update procurement and supplier settings'],
        ],
        'pos' => [
            ['name' => 'pos.access', 'description' => 'Enter and operate the POS screen'],
            ['name' => 'pos.discount', 'description' => 'Apply discounts up to 30% on line items'],
            ['name' => 'pos.approve-discount', 'description' => 'Approve discounts above 30%'],
            ['name' => 'pos.suspend-cart', 'description' => 'Suspend and resume carts'],
            ['name' => 'pos.void-cart', 'description' => 'Void any cart'],
            ['name' => 'pos.override-stock', 'description' => 'Override out-of-stock warning with manager PIN'],
            ['name' => 'pos.admin', 'description' => 'Reset PIN lockouts and manage POS sessions'],
        ],
        'sales' => [
            ['name' => 'sales.view', 'description' => 'View sale records and invoices'],
            ['name' => 'sales.import-historical', 'description' => 'Import historical sales data'],
            ['name' => 'sales.export', 'description' => 'Export sale records'],
            ['name' => 'sales.refund', 'description' => 'Process sale refunds'],
        ],
        'customers' => [
            ['name' => 'customers.view', 'description' => 'View customers and POS search'],
            ['name' => 'customers.create', 'description' => 'Create customers'],
            ['name' => 'customers.update', 'description' => 'Update customers and wallet top-ups'],
            ['name' => 'customers.delete', 'description' => 'Delete customers'],
            ['name' => 'customers.view-credit', 'description' => 'View customer credit limits and AR balances'],
            ['name' => 'customers.import', 'description' => 'Import customers from spreadsheets'],
            ['name' => 'customers.export', 'description' => 'Export customers to spreadsheets'],
            ['name' => 'customers.write-off-debt', 'description' => 'Write off customer bad debt'],
        ],
        'loyalty' => [
            ['name' => 'loyalty.view', 'description' => 'View loyalty programs and customer wallets'],
            ['name' => 'loyalty.manage', 'description' => 'Manage loyalty engine settings'],
            ['name' => 'loyalty.manage-programs', 'description' => 'Create and update loyalty programs'],
            ['name' => 'loyalty.manage-rules', 'description' => 'Manage loyalty earning and redemption rules'],
            ['name' => 'loyalty.adjust-points', 'description' => 'Manually adjust customer loyalty points'],
            ['name' => 'loyalty.approve', 'description' => 'Approve loyalty transactions requiring authorization'],
            ['name' => 'loyalty.view-transactions', 'description' => 'View loyalty transaction history'],
            ['name' => 'loyalty.manage-campaigns', 'description' => 'Manage loyalty campaigns'],
        ],
        'accounting' => [
            ['name' => 'accounting.view', 'description' => 'View accounting module and journals'],
            ['name' => 'accounting.manage-coa', 'description' => 'Manage chart of accounts'],
            ['name' => 'accounting.manage-mappings', 'description' => 'Manage GL account mappings'],
            ['name' => 'accounting.manage-posting-rules', 'description' => 'Manage posting rule sets and lines'],
            ['name' => 'accounting.create-journal', 'description' => 'Create manual journal entries'],
            ['name' => 'accounting.approve-journal', 'description' => 'Approve manual journal entries'],
            ['name' => 'accounting.post-journal', 'description' => 'Post approved journal entries'],
            ['name' => 'accounting.reverse-journal', 'description' => 'Reverse posted journal entries'],
            ['name' => 'accounting.import-coa', 'description' => 'Import chart of accounts from spreadsheets'],
            ['name' => 'accounting.import-opening-balances', 'description' => 'Import opening balances'],
            ['name' => 'accounting.manage-cost-centres', 'description' => 'Manage cost centres'],
            ['name' => 'accounting.manage-fiscal-years', 'description' => 'Manage fiscal years'],
            ['name' => 'accounting.manage-modules', 'description' => 'Enable or disable accounting sub-modules per branch'],
            ['name' => 'accounting.close-fiscal-year', 'description' => 'Close fiscal years'],
            ['name' => 'accounting.reopen-fiscal-year', 'description' => 'Reopen closed fiscal years'],
            ['name' => 'accounting.manage-bank-accounts', 'description' => 'Manage bank accounts'],
            ['name' => 'accounting.import-bank-statements', 'description' => 'Import bank statements'],
            ['name' => 'accounting.reconcile-bank', 'description' => 'Reconcile bank statements'],
            ['name' => 'accounting.manage-petty-cash', 'description' => 'Manage petty cash registers and vouchers'],
            ['name' => 'accounting.approve-petty-cash', 'description' => 'Approve or reject petty cash vouchers'],
            ['name' => 'accounting.manage-cheques', 'description' => 'Manage cheque register'],
            ['name' => 'accounting.manage-assets', 'description' => 'Manage fixed assets and depreciation'],
            ['name' => 'accounting.manage-tax-settings', 'description' => 'Manage tax types and tax accounts'],
            ['name' => 'accounting.view-reports', 'description' => 'View financial reports'],
            ['name' => 'accounting.export-reports', 'description' => 'Export financial reports'],
        ],
        'procurement' => [
            ['name' => 'procurement.view', 'description' => 'View procurement documents and suppliers'],
            ['name' => 'procurement.create', 'description' => 'Create purchase orders and requisitions'],
            ['name' => 'procurement.update', 'description' => 'Update draft procurement documents'],
            ['name' => 'procurement.delete', 'description' => 'Delete draft procurement documents'],
            ['name' => 'procurement.approve-po', 'description' => 'Approve purchase orders above threshold'],
            ['name' => 'procurement.resolve-match-exception', 'description' => 'Resolve three-way match exceptions'],
            ['name' => 'procurement.receive-grn', 'description' => 'Post goods receiving notes'],
            ['name' => 'procurement.manage-suppliers', 'description' => 'Manage supplier master data'],
            ['name' => 'procurement.process-payments', 'description' => 'Record supplier payments'],
            ['name' => 'procurement.manage-returns', 'description' => 'Manage purchase returns and RMA'],
            ['name' => 'suppliers.import', 'description' => 'Import suppliers from spreadsheets'],
            ['name' => 'suppliers.export', 'description' => 'Export suppliers to spreadsheets'],
            ['name' => 'supplier-price-lists.import', 'description' => 'Import supplier price lists from spreadsheets'],
            ['name' => 'supplier-price-lists.export', 'description' => 'Export supplier price lists to spreadsheets'],
        ],
        'hr' => [
            ['name' => 'expenses.view', 'description' => 'View expenses'],
            ['name' => 'expenses.create', 'description' => 'Create expenses'],
            ['name' => 'expenses.approve', 'description' => 'Approve expenses'],
            ['name' => 'expenses.post', 'description' => 'Post approved expenses'],
            ['name' => 'expenses.reverse', 'description' => 'Reverse posted expenses'],
            ['name' => 'expenses.manage-categories', 'description' => 'Manage expense categories'],
            ['name' => 'expenses.manage-recurring', 'description' => 'Manage recurring expense schedules'],
            ['name' => 'hr.view-employees', 'description' => 'View employees'],
            ['name' => 'hr.manage-employees', 'description' => 'Create and update employees'],
            ['name' => 'employees.import', 'description' => 'Import employees from spreadsheets'],
            ['name' => 'employees.export', 'description' => 'Export employees to spreadsheets'],
            ['name' => 'departments.import', 'description' => 'Import departments from spreadsheets'],
            ['name' => 'departments.export', 'description' => 'Export departments to spreadsheets'],
            ['name' => 'designations.import', 'description' => 'Import designations from spreadsheets'],
            ['name' => 'designations.export', 'description' => 'Export designations to spreadsheets'],
            ['name' => 'grades.import', 'description' => 'Import grades from spreadsheets'],
            ['name' => 'grades.export', 'description' => 'Export grades to spreadsheets'],
            ['name' => 'holiday-calendars.import', 'description' => 'Import holiday calendars from spreadsheets'],
            ['name' => 'holiday-calendars.export', 'description' => 'Export holiday calendars to spreadsheets'],
            ['name' => 'reporting-hierarchy.import', 'description' => 'Import reporting hierarchy from spreadsheets'],
            ['name' => 'reporting-hierarchy.export', 'description' => 'Export reporting hierarchy to spreadsheets'],
            ['name' => 'hr.manage-org', 'description' => 'Manage departments designations and grades'],
            ['name' => 'hr.manage-settings', 'description' => 'Manage HR entity settings and employment types'],
            ['name' => 'holiday.manage', 'description' => 'Manage holiday calendars and dates'],
            ['name' => 'attendance.view', 'description' => 'View attendance records'],
            ['name' => 'attendance.record', 'description' => 'Record attendance'],
            ['name' => 'attendance.adjust', 'description' => 'Adjust attendance records'],
            ['name' => 'attendance.manage-sources', 'description' => 'Manage attendance sources'],
            ['name' => 'attendance.import', 'description' => 'Import historical attendance records from spreadsheets'],
            ['name' => 'attendance.export', 'description' => 'Export attendance records to spreadsheets'],
            ['name' => 'leave.view', 'description' => 'View leave requests and balances'],
            ['name' => 'leave.request', 'description' => 'Request leave'],
            ['name' => 'leave.approve', 'description' => 'Approve leave requests'],
            ['name' => 'leave.manage-types', 'description' => 'Manage leave types'],
            ['name' => 'leave.manage-policies', 'description' => 'Manage leave policies'],
            ['name' => 'leave.manage-entitlements', 'description' => 'View and manually adjust leave entitlement balances'],
            ['name' => 'leave.request-encashment', 'description' => 'Request leave encashment'],
            ['name' => 'leave.approve-encashment', 'description' => 'Approve leave encashment requests'],
            ['name' => 'overtime.view', 'description' => 'View overtime records'],
            ['name' => 'overtime.approve', 'description' => 'Approve overtime'],
            ['name' => 'overtime.manage-policies', 'description' => 'Manage overtime policies'],
            ['name' => 'toil.request-cash-claim', 'description' => 'Request TOIL cash claims'],
            ['name' => 'toil.approve-cash-claim', 'description' => 'Approve TOIL cash claims'],
            ['name' => 'payroll.view', 'description' => 'View payroll runs'],
            ['name' => 'payroll.process', 'description' => 'Generate and process payroll runs'],
            ['name' => 'payroll.approve', 'description' => 'Approve payroll runs'],
            ['name' => 'payroll.post', 'description' => 'Post approved payroll runs'],
            ['name' => 'payroll.reverse', 'description' => 'Reverse posted payroll runs'],
            ['name' => 'payroll.manage-components', 'description' => 'Manage pay components'],
            ['name' => 'payroll.manage-structures', 'description' => 'Manage salary structures'],
            ['name' => 'payroll.manage-statutory', 'description' => 'Manage statutory schemes'],
            ['name' => 'payroll.manage-tax-slabs', 'description' => 'Manage income tax slabs'],
            ['name' => 'selfservice.view-own', 'description' => 'View own payslips attendance and leave'],
        ],
    ];

    public function run(): void
    {
        foreach (self::PERMISSIONS as $group => $permissions) {
            foreach ($permissions as $permission) {
                $displayName = AccessControlLabels::forPermission(
                    $permission['name'],
                    $permission['description'],
                );

                Permission::query()->updateOrCreate(
                    ['name' => $permission['name'], 'guard_name' => 'web'],
                    [
                        'group' => $group,
                        'description' => $permission['description'],
                        'display_name' => $displayName,
                    ],
                );
            }
        }
    }
}
