import AdminFormField from '@/Components/common/AdminFormField';
import AutoGeneratedCodeField from '@/Components/common/AutoGeneratedCodeField';
import FormCard from '@/Components/common/FormCard';
import PageHeader from '@/Components/common/PageHeader';
import Select from '@/Components/ui/select';
import { useCan } from '@/Hooks/useCan';
import AdminLayout from '@/Layouts/AdminLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { Plus, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

function previewSequentialCode(base, offset) {
    if (!base || offset === 0) {
        return base ?? '';
    }

    const match = String(base).match(/^(.*-)(\d+)$/);
    if (!match) {
        return base;
    }

    const width = match[2].length;
    const next = Number.parseInt(match[2], 10) + offset;

    return `${match[1]}${String(next).padStart(width, '0')}`;
}

function emptyZoneRow() {
    return { name: '', capacity_limit: '' };
}

function emptyBinRow() {
    return {
        warehouse_zone_id: '',
        aisle: '',
        shelf: '',
        capacity_limit: '',
    };
}

function buildZoneOptions(zones, noZoneLabel) {
    return [
        { value: '', label: noZoneLabel },
        ...zones.map((zone) => ({
            value: String(zone.id),
            label: zone.name,
        })),
    ];
}

function fieldError(errors, path) {
    return errors?.[path] ?? null;
}

function ZoneRow({ warehouse, zone, canEdit, t }) {
    const [editing, setEditing] = useState(false);
    const form = useForm({
        name: zone.name,
        capacity_limit: zone.capacity_limit ?? '',
        is_active: zone.is_active,
    });

    const save = (e) => {
        e.preventDefault();
        form.put(route('admin.warehouses.zones.update', [warehouse.id, zone.id]), {
            onSuccess: () => setEditing(false),
        });
    };

    if (editing) {
        return (
            <li className="rounded-lg border border-rp-border px-3 py-3 text-sm">
                <form onSubmit={save} className="space-y-2">
                    <AdminFormField label={t('pages.bins.fields.name')} error={form.errors.name}>
                        <input
                            className="rp-form-input w-full"
                            placeholder={t('pages.bins.placeholders.zoneName')}
                            value={form.data.name}
                            onChange={(e) => form.setData('name', e.target.value)}
                            required
                        />
                    </AdminFormField>
                    <AutoGeneratedCodeField
                        label={t('pages.bins.fields.code')}
                        value={zone.code}
                        hint={t('pages.bins.fields.codeAutoHint')}
                    />
                    <AdminFormField
                        label={t('pages.bins.fields.capacity')}
                        error={form.errors.capacity_limit}
                    >
                        <input
                            type="number"
                            min="1"
                            className="rp-form-input w-full"
                            placeholder={t('pages.bins.placeholders.capacity')}
                            value={form.data.capacity_limit}
                            onChange={(e) => form.setData('capacity_limit', e.target.value)}
                        />
                    </AdminFormField>
                    <label className="flex items-center gap-2 text-xs">
                        <input
                            type="checkbox"
                            checked={form.data.is_active}
                            onChange={(e) => form.setData('is_active', e.target.checked)}
                        />
                        {t('pages.bins.fields.active')}
                    </label>
                    <div className="flex gap-2">
                        <button type="submit" disabled={form.processing} className="rp-btn-primary text-xs">
                            {t('common.save')}
                        </button>
                        <button type="button" onClick={() => setEditing(false)} className="rp-btn-outline text-xs">
                            {t('confirm.cancel')}
                        </button>
                    </div>
                </form>
            </li>
        );
    }

    return (
        <li className="flex items-center justify-between rounded-lg border border-rp-border px-3 py-2 text-sm">
            <span>
                {zone.name} <span className="font-mono text-rp-text-muted">({zone.code})</span>
                {zone.capacity_limit != null && (
                    <span className="ml-2 text-xs text-rp-text-muted">
                        {t('pages.bins.capacityLabel', { count: zone.capacity_limit })}
                    </span>
                )}
            </span>
            <div className="flex items-center gap-2">
                {!zone.is_active && (
                    <span className="text-xs text-rp-text-muted">{t('pages.warehouses.inactive')}</span>
                )}
                {canEdit && (
                    <button type="button" onClick={() => setEditing(true)} className="rp-btn-outline text-xs">
                        {t('pages.bins.editZone')}
                    </button>
                )}
            </div>
        </li>
    );
}

function BinRow({ warehouse, bin, zones, canEdit, t }) {
    const [editing, setEditing] = useState(false);
    const form = useForm({
        warehouse_zone_id: bin.warehouse_zone_id ?? '',
        aisle: bin.aisle ?? '',
        shelf: bin.shelf ?? '',
        capacity_limit: bin.capacity_limit ?? '',
        is_active: bin.is_active,
    });

    const zoneOptions = useMemo(
        () => buildZoneOptions(zones, t('pages.bins.noZone')),
        [zones, t],
    );

    const save = (e) => {
        e.preventDefault();
        form.put(route('admin.warehouses.bins.update', [warehouse.id, bin.id]), {
            onSuccess: () => setEditing(false),
        });
    };

    if (editing) {
        return (
            <tr className="border-b border-rp-border/50 bg-rp-surface-muted/40">
                <td colSpan={5} className="px-3 py-3">
                    <form onSubmit={save} className="grid gap-2 sm:grid-cols-2">
                        <AdminFormField label={t('pages.bins.fields.zone')} error={form.errors.warehouse_zone_id}>
                            <Select
                                options={zoneOptions}
                                value={form.data.warehouse_zone_id ? String(form.data.warehouse_zone_id) : ''}
                                onChange={(value) => form.setData('warehouse_zone_id', value ?? '')}
                                placeholder={t('pages.bins.placeholders.zone')}
                            />
                        </AdminFormField>
                        <AutoGeneratedCodeField
                            label={t('pages.bins.fields.binCode')}
                            value={bin.bin_code}
                            hint={t('pages.bins.fields.codeAutoHint')}
                        />
                        <AdminFormField label={t('pages.bins.fields.aisle')} error={form.errors.aisle}>
                            <input
                                className="rp-form-input w-full"
                                placeholder={t('pages.bins.placeholders.aisle')}
                                value={form.data.aisle}
                                onChange={(e) => form.setData('aisle', e.target.value)}
                            />
                        </AdminFormField>
                        <AdminFormField label={t('pages.bins.fields.shelf')} error={form.errors.shelf}>
                            <input
                                className="rp-form-input w-full"
                                placeholder={t('pages.bins.placeholders.shelf')}
                                value={form.data.shelf}
                                onChange={(e) => form.setData('shelf', e.target.value)}
                            />
                        </AdminFormField>
                        <AdminFormField
                            label={t('pages.bins.fields.capacity')}
                            error={form.errors.capacity_limit}
                        >
                            <input
                                type="number"
                                min="1"
                                className="rp-form-input w-full"
                                placeholder={t('pages.bins.placeholders.capacity')}
                                value={form.data.capacity_limit}
                                onChange={(e) => form.setData('capacity_limit', e.target.value)}
                            />
                        </AdminFormField>
                        <label className="flex items-center gap-2 text-xs">
                            <input
                                type="checkbox"
                                checked={form.data.is_active}
                                onChange={(e) => form.setData('is_active', e.target.checked)}
                            />
                            {t('pages.bins.fields.active')}
                        </label>
                        <div className="flex gap-2 sm:col-span-2">
                            <button type="submit" disabled={form.processing} className="rp-btn-primary text-xs">
                                {t('common.save')}
                            </button>
                            <button type="button" onClick={() => setEditing(false)} className="rp-btn-outline text-xs">
                                {t('confirm.cancel')}
                            </button>
                        </div>
                    </form>
                </td>
            </tr>
        );
    }

    return (
        <tr className="border-b border-rp-border/50">
            <td className="py-2 font-mono">
                {bin.bin_code}
                {!bin.is_active && (
                    <span className="ml-2 text-xs text-rp-text-muted">{t('pages.warehouses.inactive')}</span>
                )}
            </td>
            <td className="py-2">{bin.zone_name ?? '—'}</td>
            <td className="py-2 text-rp-text-muted">
                {[bin.aisle, bin.shelf].filter(Boolean).join('-') || '—'}
            </td>
            <td className="py-2 text-rp-text-muted">{bin.capacity_limit ?? '—'}</td>
            <td className="py-2 text-right">
                {canEdit && (
                    <button type="button" onClick={() => setEditing(true)} className="rp-btn-outline text-xs">
                        {t('pages.bins.editBin')}
                    </button>
                )}
            </td>
        </tr>
    );
}

export default function BinsIndex({ warehouse, zones, bins, nextZoneCode = '', nextBinCode = '' }) {
    const can = useCan();
    const { t } = useTranslation();
    const canEdit = can('inventory.manage-bins');
    const [showZoneForm, setShowZoneForm] = useState(false);
    const [showBinForm, setShowBinForm] = useState(false);

    const zoneForm = useForm({ zones: [emptyZoneRow()] });
    const binForm = useForm({ bins: [emptyBinRow()] });

    const zoneOptions = useMemo(
        () => buildZoneOptions(zones, t('pages.bins.noZone')),
        [zones, t],
    );

    const updateZoneRow = (index, patch) => {
        zoneForm.setData(
            'zones',
            zoneForm.data.zones.map((row, i) => (i === index ? { ...row, ...patch } : row)),
        );
    };

    const addZoneRow = () => {
        zoneForm.setData('zones', [...zoneForm.data.zones, emptyZoneRow()]);
    };

    const removeZoneRow = (index) => {
        if (zoneForm.data.zones.length <= 1) {
            return;
        }
        zoneForm.setData(
            'zones',
            zoneForm.data.zones.filter((_, i) => i !== index),
        );
    };

    const updateBinRow = (index, patch) => {
        binForm.setData(
            'bins',
            binForm.data.bins.map((row, i) => (i === index ? { ...row, ...patch } : row)),
        );
    };

    const addBinRow = () => {
        binForm.setData('bins', [...binForm.data.bins, emptyBinRow()]);
    };

    const removeBinRow = (index) => {
        if (binForm.data.bins.length <= 1) {
            return;
        }
        binForm.setData(
            'bins',
            binForm.data.bins.filter((_, i) => i !== index),
        );
    };

    const submitZone = (e) => {
        e.preventDefault();

        const payload = zoneForm.data.zones
            .filter((row) => String(row.name ?? '').trim() !== '')
            .map((row) => ({
                name: String(row.name).trim(),
                capacity_limit: row.capacity_limit === '' ? null : row.capacity_limit,
            }));

        if (payload.length === 0) {
            zoneForm.setError('zones', t('pages.bins.validation.atLeastOneZone'));
            return;
        }

        zoneForm.transform(() => ({ zones: payload }));
        zoneForm.post(route('admin.warehouses.zones.store', warehouse.id), {
            onSuccess: () => {
                zoneForm.reset();
                zoneForm.setData({ zones: [emptyZoneRow()] });
                setShowZoneForm(false);
            },
            onFinish: () => zoneForm.transform((data) => data),
        });
    };

    const submitBin = (e) => {
        e.preventDefault();

        const payload = binForm.data.bins.map((row) => ({
            warehouse_zone_id: row.warehouse_zone_id || null,
            aisle: String(row.aisle ?? '').trim() || null,
            shelf: String(row.shelf ?? '').trim() || null,
            capacity_limit: row.capacity_limit === '' ? null : row.capacity_limit,
        }));

        if (payload.length === 0) {
            binForm.setError('bins', t('pages.bins.validation.atLeastOneBin'));
            return;
        }

        binForm.transform(() => ({ bins: payload }));
        binForm.post(route('admin.warehouses.bins.store', warehouse.id), {
            onSuccess: () => {
                binForm.reset();
                binForm.setData({ bins: [emptyBinRow()] });
                setShowBinForm(false);
            },
            onFinish: () => binForm.transform((data) => data),
        });
    };

    const openZoneForm = () => {
        zoneForm.clearErrors();
        zoneForm.setData({ zones: [emptyZoneRow()] });
        setShowZoneForm(true);
    };

    const openBinForm = () => {
        binForm.clearErrors();
        binForm.setData({ bins: [emptyBinRow()] });
        setShowBinForm(true);
    };

    return (
        <AdminLayout>
            <Head title={t('pages.bins.title', { warehouse: warehouse.name })} />
            <PageHeader
                title={t('pages.bins.title', { warehouse: warehouse.name })}
                description={warehouse.branch_name}
            >
                <Link href={route('admin.warehouses.edit', warehouse.id)} className="rp-btn-outline">
                    {t('pages.bins.backToWarehouse')}
                </Link>
            </PageHeader>

            <div className="grid gap-6 lg:grid-cols-2">
                <FormCard title={t('pages.bins.zones')}>
                    {canEdit && (
                        <button
                            type="button"
                            onClick={() => (showZoneForm ? setShowZoneForm(false) : openZoneForm())}
                            className="rp-btn-outline mb-4 text-sm"
                        >
                            {showZoneForm ? t('confirm.cancel') : t('pages.bins.addZone')}
                        </button>
                    )}
                    {showZoneForm && (
                        <form onSubmit={submitZone} className="mb-4 space-y-3 border-b border-rp-border pb-4">
                            {fieldError(zoneForm.errors, 'zones') && (
                                <p className="text-xs text-rose-500">{fieldError(zoneForm.errors, 'zones')}</p>
                            )}
                            {zoneForm.data.zones.map((row, index) => (
                                <div
                                    key={index}
                                    className="space-y-2 rounded-lg border border-rp-border/70 p-3"
                                >
                                    <div className="flex items-center justify-between gap-2">
                                        <p className="text-xs font-medium text-rp-text-muted">
                                            {t('pages.bins.zoneRow', { number: index + 1 })}
                                        </p>
                                        {zoneForm.data.zones.length > 1 && (
                                            <button
                                                type="button"
                                                onClick={() => removeZoneRow(index)}
                                                className="rp-btn-outline text-xs"
                                                aria-label={t('pages.bins.removeRow')}
                                            >
                                                <Trash2 className="h-3.5 w-3.5" />
                                            </button>
                                        )}
                                    </div>
                                    <AdminFormField
                                        label={t('pages.bins.fields.name')}
                                        error={fieldError(zoneForm.errors, `zones.${index}.name`)}
                                    >
                                        <input
                                            className="rp-form-input w-full"
                                            placeholder={t('pages.bins.placeholders.zoneName')}
                                            value={row.name}
                                            onChange={(e) => updateZoneRow(index, { name: e.target.value })}
                                            required
                                        />
                                    </AdminFormField>
                                    <AutoGeneratedCodeField
                                        id={`zone-code-${index}`}
                                        label={t('pages.bins.fields.code')}
                                        value={previewSequentialCode(nextZoneCode, index)}
                                        hint={t('pages.bins.fields.codeAutoHint')}
                                        error={fieldError(zoneForm.errors, `zones.${index}.code`)}
                                    />
                                    <AdminFormField
                                        label={t('pages.bins.fields.capacity')}
                                        error={fieldError(zoneForm.errors, `zones.${index}.capacity_limit`)}
                                    >
                                        <input
                                            type="number"
                                            min="1"
                                            className="rp-form-input w-full"
                                            placeholder={t('pages.bins.placeholders.capacity')}
                                            value={row.capacity_limit}
                                            onChange={(e) =>
                                                updateZoneRow(index, { capacity_limit: e.target.value })
                                            }
                                        />
                                    </AdminFormField>
                                </div>
                            ))}
                            <div className="flex flex-wrap gap-2">
                                <button type="button" onClick={addZoneRow} className="rp-btn-outline text-sm">
                                    <Plus className="h-3.5 w-3.5" />
                                    {t('pages.bins.addMore')}
                                </button>
                                <button
                                    type="submit"
                                    disabled={zoneForm.processing}
                                    className="rp-btn-primary text-sm"
                                >
                                    {t('pages.bins.saveZones')}
                                </button>
                            </div>
                        </form>
                    )}
                    <ul className="space-y-2">
                        {zones.map((zone) => (
                            <ZoneRow
                                key={zone.id}
                                warehouse={warehouse}
                                zone={zone}
                                canEdit={canEdit}
                                t={t}
                            />
                        ))}
                        {zones.length === 0 && (
                            <p className="text-sm text-rp-text-muted">{t('pages.bins.noZones')}</p>
                        )}
                    </ul>
                </FormCard>

                <FormCard title={t('pages.bins.binLocations')}>
                    {canEdit && (
                        <button
                            type="button"
                            onClick={() => (showBinForm ? setShowBinForm(false) : openBinForm())}
                            className="rp-btn-outline mb-4 text-sm"
                        >
                            {showBinForm ? t('confirm.cancel') : t('pages.bins.addBin')}
                        </button>
                    )}
                    {showBinForm && (
                        <form onSubmit={submitBin} className="mb-4 space-y-3 border-b border-rp-border pb-4">
                            {fieldError(binForm.errors, 'bins') && (
                                <p className="text-xs text-rose-500">{fieldError(binForm.errors, 'bins')}</p>
                            )}
                            {binForm.data.bins.map((row, index) => (
                                <div
                                    key={index}
                                    className="space-y-2 rounded-lg border border-rp-border/70 p-3"
                                >
                                    <div className="flex items-center justify-between gap-2">
                                        <p className="text-xs font-medium text-rp-text-muted">
                                            {t('pages.bins.binRow', { number: index + 1 })}
                                        </p>
                                        {binForm.data.bins.length > 1 && (
                                            <button
                                                type="button"
                                                onClick={() => removeBinRow(index)}
                                                className="rp-btn-outline text-xs"
                                                aria-label={t('pages.bins.removeRow')}
                                            >
                                                <Trash2 className="h-3.5 w-3.5" />
                                            </button>
                                        )}
                                    </div>
                                    <AdminFormField
                                        label={t('pages.bins.fields.zone')}
                                        error={fieldError(binForm.errors, `bins.${index}.warehouse_zone_id`)}
                                    >
                                        <Select
                                            options={zoneOptions}
                                            value={row.warehouse_zone_id ? String(row.warehouse_zone_id) : ''}
                                            onChange={(value) =>
                                                updateBinRow(index, { warehouse_zone_id: value ?? '' })
                                            }
                                            placeholder={t('pages.bins.placeholders.zone')}
                                        />
                                    </AdminFormField>
                                    <div className="grid grid-cols-2 gap-2">
                                        <AdminFormField
                                            label={t('pages.bins.fields.aisle')}
                                            error={fieldError(binForm.errors, `bins.${index}.aisle`)}
                                        >
                                            <input
                                                className="rp-form-input w-full"
                                                placeholder={t('pages.bins.placeholders.aisle')}
                                                value={row.aisle}
                                                onChange={(e) => updateBinRow(index, { aisle: e.target.value })}
                                            />
                                        </AdminFormField>
                                        <AdminFormField
                                            label={t('pages.bins.fields.shelf')}
                                            error={fieldError(binForm.errors, `bins.${index}.shelf`)}
                                        >
                                            <input
                                                className="rp-form-input w-full"
                                                placeholder={t('pages.bins.placeholders.shelf')}
                                                value={row.shelf}
                                                onChange={(e) => updateBinRow(index, { shelf: e.target.value })}
                                            />
                                        </AdminFormField>
                                    </div>
                                    <AutoGeneratedCodeField
                                        id={`bin-code-${index}`}
                                        label={t('pages.bins.fields.binCode')}
                                        value={previewSequentialCode(nextBinCode, index)}
                                        hint={t('pages.bins.fields.codeAutoHint')}
                                        error={fieldError(binForm.errors, `bins.${index}.bin_code`)}
                                    />
                                    <AdminFormField
                                        label={t('pages.bins.fields.capacity')}
                                        error={fieldError(binForm.errors, `bins.${index}.capacity_limit`)}
                                    >
                                        <input
                                            type="number"
                                            min="1"
                                            className="rp-form-input w-full"
                                            placeholder={t('pages.bins.placeholders.capacity')}
                                            value={row.capacity_limit}
                                            onChange={(e) =>
                                                updateBinRow(index, { capacity_limit: e.target.value })
                                            }
                                        />
                                    </AdminFormField>
                                </div>
                            ))}
                            <div className="flex flex-wrap gap-2">
                                <button type="button" onClick={addBinRow} className="rp-btn-outline text-sm">
                                    <Plus className="h-3.5 w-3.5" />
                                    {t('pages.bins.addMore')}
                                </button>
                                <button
                                    type="submit"
                                    disabled={binForm.processing}
                                    className="rp-btn-primary text-sm"
                                >
                                    {t('pages.bins.saveBins')}
                                </button>
                            </div>
                        </form>
                    )}
                    <div className="overflow-x-auto">
                        <table className="w-full text-sm">
                            <thead>
                                <tr className="border-b border-rp-border text-left text-rp-text-muted">
                                    <th className="py-2">{t('pages.bins.fields.binCode')}</th>
                                    <th className="py-2">{t('pages.bins.fields.zone')}</th>
                                    <th className="py-2">{t('pages.bins.fields.location')}</th>
                                    <th className="py-2">{t('pages.bins.fields.capacity')}</th>
                                    <th className="py-2" />
                                </tr>
                            </thead>
                            <tbody>
                                {bins.map((bin) => (
                                    <BinRow
                                        key={bin.id}
                                        warehouse={warehouse}
                                        bin={bin}
                                        zones={zones}
                                        canEdit={canEdit}
                                        t={t}
                                    />
                                ))}
                            </tbody>
                        </table>
                        {bins.length === 0 && (
                            <p className="py-4 text-sm text-rp-text-muted">{t('pages.bins.noBins')}</p>
                        )}
                    </div>
                </FormCard>
            </div>
        </AdminLayout>
    );
}
