import {
    Building2,
    Boxes,
    CalendarClock,
    ClipboardList,
    FolderTree,
    KeyRound,
    LayoutDashboard,
    Monitor,
    Receipt,
    Settings2,
    Package,
    Scale,
    Shield,
    ShieldAlert,
    Tag,
    Timer,
    Truck,
    UserRound,
    Users,
    UsersRound,
    Warehouse,
} from 'lucide-react';

export const ADMIN_NAV_SECTIONS = [
    {
        label: 'Overview',
        labelKey: 'overview',
        items: [
            {
                label: 'Dashboard',
                labelKey: 'dashboard',
                href: 'admin.dashboard',
                routeName: 'admin.dashboard',
                permission: 'admin.dashboard.view',
                icon: LayoutDashboard,
                keywords: ['home', 'overview', 'stats'],
            },
            {
                label: 'Point of Sale',
                labelKey: 'pos',
                href: 'admin.pos.index',
                routeName: 'admin.pos.*',
                permission: 'pos.access',
                icon: Monitor,
                keywords: ['pos', 'cashier', 'register', 'checkout', 'sale'],
            },
            {
                label: 'Sales',
                labelKey: 'sales',
                href: 'admin.sales.index',
                routeName: 'admin.sales.*',
                permission: 'sales.view',
                icon: Receipt,
                keywords: ['sales', 'invoices', 'transactions', 'receipts'],
            },
        ],
    },
    {
        label: 'Organization',
        labelKey: 'organization',
        items: [
            {
                label: 'Branches',
                labelKey: 'branches',
                href: 'admin.branches.index',
                routeName: 'admin.branches.*',
                permission: 'branches.view',
                icon: Building2,
                keywords: ['stores', 'locations', 'outlets'],
            },
            {
                label: 'Warehouses',
                labelKey: 'warehouses',
                href: 'admin.warehouses.index',
                routeName: 'admin.warehouses.*',
                permission: 'warehouses.view',
                icon: Boxes,
                keywords: ['storage', 'depot', 'location'],
            },
        ],
    },
    {
        label: 'Inventory',
        labelKey: 'inventorySection',
        items: [
            {
                label: 'Stock levels',
                labelKey: 'inventory',
                href: 'admin.inventory.index',
                routeName: 'admin.inventory.*',
                activeRoutes: [
                    'admin.inventory.index',
                    'admin.inventory.adjust',
                    'admin.inventory.receive',
                ],
                permission: 'inventory.view',
                icon: Warehouse,
                keywords: ['stock', 'warehouse', 'on hand', 'quantity'],
            },
            {
                label: 'Transfers',
                labelKey: 'stockTransfers',
                href: 'admin.stock-transfers.index',
                routeName: 'admin.stock-transfers.*',
                permission: 'inventory.transfer',
                icon: Truck,
                keywords: ['transfer', 'ship', 'receive'],
            },
            {
                label: 'Suppliers',
                labelKey: 'suppliers',
                href: 'admin.suppliers.index',
                routeName: 'admin.suppliers.*',
                permission: 'procurement.manage-suppliers',
                icon: UserRound,
                keywords: ['supplier', 'vendor', 'procurement'],
            },
            {
                label: 'Purchase Orders',
                labelKey: 'purchaseOrders',
                href: 'admin.purchase-orders.index',
                routeName: 'admin.purchase-orders.*',
                permission: 'procurement.view',
                icon: ClipboardList,
                keywords: ['po', 'purchase', 'order', 'procurement'],
            },
            {
                label: 'Goods Receiving',
                labelKey: 'goodsReceiving',
                href: 'admin.goods-receiving-notes.index',
                routeName: 'admin.goods-receiving-notes.*',
                permission: 'procurement.view',
                icon: Package,
                keywords: ['grn', 'receiving', 'receipt', 'procurement'],
            },
            {
                label: 'Procurement Reports',
                labelKey: 'procurementReports',
                href: 'admin.procurement.reports',
                routeName: 'admin.procurement.reports',
                permission: 'procurement.view',
                icon: ClipboardList,
                keywords: ['procurement', 'reports', 'payables', 'open po'],
            },
            {
                label: 'Bin stock',
                labelKey: 'binStock',
                href: 'admin.inventory.bin-report',
                routeName: 'admin.inventory.bin-report',
                permission: 'inventory.reports',
                icon: Boxes,
                keywords: ['bin', 'location', 'zone', 'aisle'],
            },
            {
                label: 'Bin transfer',
                labelKey: 'binTransfer',
                href: 'admin.inventory.bin-transfer.form',
                routeName: 'admin.inventory.bin-transfer.form',
                permission: 'inventory.manage-bins',
                icon: Truck,
                keywords: ['bin', 'transfer', 'move', 'relocate'],
            },
            {
                label: 'Branch stock settings',
                labelKey: 'branchStockSettings',
                href: 'admin.inventory.branch-stock-settings',
                routeName: 'admin.inventory.branch-stock-settings',
                permission: 'inventory.adjust',
                icon: Scale,
                keywords: ['reorder', 'safety stock', 'branch', 'threshold'],
            },
            {
                label: 'Quarantine',
                labelKey: 'quarantine',
                href: 'admin.inventory.quarantine',
                routeName: 'admin.inventory.quarantine',
                permission: 'inventory.release-quarantine',
                icon: ShieldAlert,
                keywords: ['qc', 'quality', 'hold', 'pending'],
            },
            {
                label: 'Cycle counts',
                labelKey: 'cycleCounts',
                href: 'admin.count-sessions.index',
                routeName: 'admin.count-sessions.*',
                permission: 'inventory.cycle-count',
                icon: ClipboardList,
                keywords: ['count', 'stocktake', 'physical', 'variance'],
            },
            {
                label: 'Count schedules',
                labelKey: 'countSchedules',
                href: 'admin.count-schedule-rules.index',
                routeName: 'admin.count-schedule-rules.*',
                permission: 'inventory.cycle-count',
                icon: CalendarClock,
                keywords: ['schedule', 'recurring', 'automatic', 'count'],
            },
        ],
    },
    {
        label: 'Catalog',
        labelKey: 'catalog',
        items: [
            {
                label: 'Products',
                labelKey: 'products',
                href: 'admin.products.index',
                routeName: 'admin.products.*',
                permission: 'products.view',
                icon: Package,
                keywords: ['items', 'sku', 'inventory', 'pim'],
            },
            {
                label: 'Categories',
                labelKey: 'categories',
                href: 'admin.categories.index',
                routeName: 'admin.categories.*',
                permission: 'products.view',
                icon: FolderTree,
                keywords: ['taxonomy', 'groups'],
            },
            {
                label: 'Brands',
                labelKey: 'brands',
                href: 'admin.brands.index',
                routeName: 'admin.brands.*',
                permission: 'products.view',
                icon: Tag,
                keywords: ['manufacturer', 'vendor'],
            },
            {
                label: 'Units',
                labelKey: 'units',
                href: 'admin.units.index',
                routeName: 'admin.units.*',
                permission: 'products.view',
                icon: Scale,
                keywords: ['measurement', 'uom', 'kg', 'liter', 'each'],
            },
        ],
    },
    {
        label: 'Customers',
        labelKey: 'customersSection',
        items: [
            {
                label: 'Customers',
                labelKey: 'customers',
                href: 'admin.customers.index',
                routeName: 'admin.customers.*',
                permission: 'customers.view',
                icon: UserRound,
                keywords: ['crm', 'loyalty', 'wallet', 'credit'],
            },
            {
                label: 'Customer Groups',
                labelKey: 'customerGroups',
                href: 'admin.customer-groups.index',
                routeName: 'admin.customer-groups.*',
                permission: 'customers.view',
                icon: UsersRound,
                keywords: ['wholesale', 'vip', 'pricing group'],
            },
            {
                label: 'AR Aging',
                labelKey: 'arAging',
                href: 'admin.ar-aging.index',
                routeName: 'admin.ar-aging.*',
                permission: 'customers.view-credit',
                icon: Timer,
                keywords: ['receivable', 'outstanding', 'aging', 'credit'],
            },
        ],
    },
    {
        label: 'Admin',
        labelKey: 'admin',
        items: [
            {
                label: 'Users',
                labelKey: 'users',
                href: 'admin.users.index',
                routeName: 'admin.users.*',
                permission: 'users.view',
                icon: Users,
                keywords: ['team', 'staff', 'members'],
            },
            {
                label: 'Roles',
                labelKey: 'roles',
                href: 'admin.roles.index',
                routeName: 'admin.roles.*',
                permission: 'roles.view',
                icon: Shield,
                keywords: ['access', 'profiles'],
            },
            {
                label: 'Permissions',
                labelKey: 'permissions',
                href: 'admin.permissions.index',
                routeName: 'admin.permissions.*',
                permission: 'permissions.view',
                icon: KeyRound,
                keywords: ['capabilities', 'acl'],
            },
            {
                label: 'Settings',
                labelKey: 'settings',
                href: 'admin.settings.index',
                routeName: 'admin.settings.*',
                permission: 'settings.view',
                permissionsAny: [
                    'settings.view',
                    'settings.general.update',
                    'settings.company.update',
                    'settings.notifications.update',
                    'settings.import-export.update',
                ],
                icon: Settings2,
                keywords: ['configuration', 'preferences', 'global'],
            },
        ],
    },
];
