import {
    AlertCircle,
    BarChart3,
    BookOpen,
    Building2,
    Boxes,
    CalendarClock,
    ClipboardList,
    FileSpreadsheet,
    FolderTree,
    Gift,
    KeyRound,
    Landmark,
    LayoutDashboard,
    Link2,
    Monitor,
    Receipt,
    ScrollText,
    Settings2,
    Layers,
    Coins,
    Package,
    Scale,
    Shield,
    ShieldAlert,
    Tag,
    Timer,
    Truck,
    UserRound,
    Users,
    UsersRound,
    Wallet,
    Warehouse,
} from 'lucide-react';

export const ADMIN_NAV_SECTIONS = [
    {
        label: 'Overview',
        labelKey: 'overview',
        items: [
            {
                label: 'Dashboard',
                labelKey: 'dashboard',
                href: 'admin.dashboard',
                routeName: 'admin.dashboard',
                permission: 'admin.dashboard.view',
                icon: LayoutDashboard,
                keywords: ['home', 'overview', 'stats'],
            },
            {
                label: 'Point of Sale',
                labelKey: 'pos',
                href: 'admin.pos.index',
                routeName: 'admin.pos.*',
                permission: 'pos.access',
                icon: Monitor,
                keywords: ['pos', 'cashier', 'register', 'checkout', 'sale'],
            },
            {
                label: 'Sales',
                labelKey: 'sales',
                href: 'admin.sales.index',
                routeName: 'admin.sales.*',
                permission: 'sales.view',
                icon: Receipt,
                keywords: ['sales', 'invoices', 'transactions', 'receipts'],
            },
        ],
    },
    {
        label: 'Organization',
        labelKey: 'organization',
        items: [
            {
                label: 'Branches',
                labelKey: 'branches',
                href: 'admin.branches.index',
                routeName: 'admin.branches.*',
                permission: 'branches.view',
                icon: Building2,
                keywords: ['stores', 'locations', 'outlets'],
            },
            {
                label: 'Warehouses',
                labelKey: 'warehouses',
                href: 'admin.warehouses.index',
                routeName: 'admin.warehouses.*',
                permission: 'warehouses.view',
                icon: Boxes,
                keywords: ['storage', 'depot', 'location'],
            },
        ],
    },
    {
        label: 'Inventory',
        labelKey: 'inventorySection',
        items: [
            {
                label: 'Stock levels',
                labelKey: 'inventory',
                href: 'admin.inventory.index',
                routeName: 'admin.inventory.*',
                activeRoutes: [
                    'admin.inventory.index',
                    'admin.inventory.adjust',
                    'admin.inventory.receive',
                ],
                permission: 'inventory.view',
                icon: Warehouse,
                keywords: ['stock', 'warehouse', 'on hand', 'quantity'],
            },
            {
                label: 'Transfers',
                labelKey: 'stockTransfers',
                href: 'admin.stock-transfers.index',
                routeName: 'admin.stock-transfers.*',
                permission: 'inventory.transfer',
                icon: Truck,
                keywords: ['transfer', 'ship', 'receive'],
            },
            {
                label: 'Suppliers',
                labelKey: 'suppliers',
                href: 'admin.suppliers.index',
                routeName: 'admin.suppliers.*',
                permission: 'procurement.manage-suppliers',
                icon: UserRound,
                keywords: ['supplier', 'vendor', 'procurement'],
            },
            {
                label: 'Purchase Orders',
                labelKey: 'purchaseOrders',
                href: 'admin.purchase-orders.index',
                routeName: 'admin.purchase-orders.*',
                permission: 'procurement.view',
                icon: ClipboardList,
                keywords: ['po', 'purchase', 'order', 'procurement'],
            },
            {
                label: 'Goods Receiving',
                labelKey: 'goodsReceiving',
                href: 'admin.goods-receiving-notes.index',
                routeName: 'admin.goods-receiving-notes.*',
                permission: 'procurement.view',
                icon: Package,
                keywords: ['grn', 'receiving', 'receipt', 'procurement'],
            },
            {
                label: 'Supplier Price Lists',
                labelKey: 'supplierPriceLists',
                href: 'admin.supplier-price-lists.index',
                routeName: 'admin.supplier-price-lists.*',
                permission: 'procurement.manage-suppliers',
                icon: Tag,
                keywords: ['price list', 'contract', 'supplier pricing', 'procurement'],
            },
            {
                label: 'Procurement Reports',
                labelKey: 'procurementReports',
                href: 'admin.procurement.reports',
                routeName: 'admin.procurement.reports',
                permission: 'procurement.view',
                icon: ClipboardList,
                keywords: ['procurement', 'reports', 'payables', 'open po'],
            },
            {
                label: 'Bin stock',
                labelKey: 'binStock',
                href: 'admin.inventory.bin-report',
                routeName: 'admin.inventory.bin-report',
                permission: 'inventory.reports',
                icon: Boxes,
                keywords: ['bin', 'location', 'zone', 'aisle'],
            },
            {
                label: 'Bin transfer',
                labelKey: 'binTransfer',
                href: 'admin.inventory.bin-transfer.form',
                routeName: 'admin.inventory.bin-transfer.form',
                permission: 'inventory.manage-bins',
                icon: Truck,
                keywords: ['bin', 'transfer', 'move', 'relocate'],
            },
            {
                label: 'Branch stock settings',
                labelKey: 'branchStockSettings',
                href: 'admin.inventory.branch-stock-settings',
                routeName: 'admin.inventory.branch-stock-settings',
                permission: 'inventory.adjust',
                icon: Scale,
                keywords: ['reorder', 'safety stock', 'branch', 'threshold'],
            },
            {
                label: 'Quarantine',
                labelKey: 'quarantine',
                href: 'admin.inventory.quarantine',
                routeName: 'admin.inventory.quarantine',
                permission: 'inventory.release-quarantine',
                icon: ShieldAlert,
                keywords: ['qc', 'quality', 'hold', 'pending'],
            },
            {
                label: 'Cycle counts',
                labelKey: 'cycleCounts',
                href: 'admin.count-sessions.index',
                routeName: 'admin.count-sessions.*',
                permission: 'inventory.cycle-count',
                icon: ClipboardList,
                keywords: ['count', 'stocktake', 'physical', 'variance'],
            },
            {
                label: 'Count schedules',
                labelKey: 'countSchedules',
                href: 'admin.count-schedule-rules.index',
                routeName: 'admin.count-schedule-rules.*',
                permission: 'inventory.cycle-count',
                icon: CalendarClock,
                keywords: ['schedule', 'recurring', 'automatic', 'count'],
            },
        ],
    },
    {
        label: 'Catalog',
        labelKey: 'catalog',
        items: [
            {
                label: 'Products',
                labelKey: 'products',
                href: 'admin.products.index',
                routeName: 'admin.products.*',
                permission: 'products.view',
                icon: Package,
                keywords: ['items', 'sku', 'inventory', 'pim'],
            },
            {
                label: 'Categories',
                labelKey: 'categories',
                href: 'admin.categories.index',
                routeName: 'admin.categories.*',
                permission: 'products.view',
                icon: FolderTree,
                keywords: ['taxonomy', 'groups'],
            },
            {
                label: 'Brands',
                labelKey: 'brands',
                href: 'admin.brands.index',
                routeName: 'admin.brands.*',
                permission: 'products.view',
                icon: Tag,
                keywords: ['manufacturer', 'vendor'],
            },
            {
                label: 'Units',
                labelKey: 'units',
                href: 'admin.units.index',
                routeName: 'admin.units.*',
                permission: 'products.view',
                icon: Scale,
                keywords: ['measurement', 'uom', 'kg', 'liter', 'each'],
            },
        ],
    },
    {
        label: 'Customers',
        labelKey: 'customersSection',
        items: [
            {
                label: 'Customers',
                labelKey: 'customers',
                href: 'admin.customers.index',
                routeName: 'admin.customers.*',
                permission: 'customers.view',
                icon: UserRound,
                keywords: ['crm', 'loyalty', 'wallet', 'credit'],
            },
            {
                label: 'Customer Groups',
                labelKey: 'customerGroups',
                href: 'admin.customer-groups.index',
                routeName: 'admin.customer-groups.*',
                permission: 'customers.view',
                icon: UsersRound,
                keywords: ['wholesale', 'vip', 'pricing group'],
            },
            {
                label: 'AR Aging',
                labelKey: 'arAging',
                href: 'admin.ar-aging.index',
                routeName: 'admin.ar-aging.*',
                permission: 'customers.view-credit',
                icon: Timer,
                keywords: ['receivable', 'outstanding', 'aging', 'credit'],
            },
            {
                label: 'Loyalty Programs',
                labelKey: 'loyaltyPrograms',
                href: 'admin.loyalty.programs.index',
                routeName: 'admin.loyalty.programs.*',
                permission: 'loyalty.view',
                icon: Gift,
                keywords: ['rewards', 'points', 'tiers', 'campaigns'],
            },
            {
                label: 'Loyalty Reports',
                labelKey: 'loyaltyReports',
                href: 'admin.loyalty.reports.index',
                routeName: 'admin.loyalty.reports.*',
                permission: 'loyalty.view',
                icon: Receipt,
                keywords: ['points earned', 'redemption', 'tier distribution'],
            },
            {
                label: 'Loyalty Transactions',
                labelKey: 'loyaltyTransactions',
                href: 'admin.loyalty.transactions.index',
                routeName: 'admin.loyalty.transactions.*',
                permission: 'loyalty.view-transactions',
                icon: ClipboardList,
                keywords: ['points', 'approval', 'redemption', 'adjustment'],
            },
        ],
    },
    {
        label: 'Accounting',
        labelKey: 'accountingSection',
        items: [
            {
                label: 'Chart of Accounts',
                labelKey: 'chartOfAccounts',
                href: 'admin.accounting.chart-of-accounts.index',
                routeName: 'admin.accounting.chart-of-accounts.*',
                permission: 'accounting.view',
                icon: BookOpen,
                keywords: ['coa', 'gl', 'ledger', 'accounts'],
            },
            {
                label: 'Account Mappings',
                labelKey: 'accountMappings',
                href: 'admin.accounting.account-mappings.index',
                routeName: 'admin.accounting.account-mappings.*',
                permission: 'accounting.manage-mappings',
                icon: Link2,
                keywords: ['mapping', 'gl', 'resolver'],
            },
            {
                label: 'Posting Rules',
                labelKey: 'postingRules',
                href: 'admin.accounting.posting-rules.index',
                routeName: 'admin.accounting.posting-rules.*',
                permission: 'accounting.manage-posting-rules',
                icon: FileSpreadsheet,
                keywords: ['posting', 'rules', 'journal', 'auto-post'],
            },
            {
                label: 'Journal Entries',
                labelKey: 'journalEntries',
                href: 'admin.accounting.journal-entries.index',
                routeName: 'admin.accounting.journal-entries.*',
                permission: 'accounting.view',
                icon: ScrollText,
                keywords: ['journal', 'voucher', 'manual entry', 'gl'],
            },
            {
                label: 'Cost Centres',
                labelKey: 'costCentres',
                href: 'admin.accounting.cost-centres.index',
                routeName: 'admin.accounting.cost-centres.*',
                permission: 'accounting.manage-cost-centres',
                permissionsAny: ['accounting.manage-cost-centres', 'accounting.view'],
                module: 'cost_centres',
                icon: Layers,
                keywords: ['cost centre', 'department', 'allocation'],
            },
            {
                label: 'Financial Settings',
                labelKey: 'accountingSettings',
                href: 'admin.accounting.settings.index',
                routeName: 'admin.accounting.settings.*',
                permission: 'accounting.manage-fiscal-years',
                permissionsAny: ['accounting.manage-fiscal-years', 'accounting.view'],
                icon: Settings2,
                keywords: ['fiscal year', 'cutover', 'retained earnings'],
            },
            {
                label: 'Financial Reports',
                labelKey: 'accountingReports',
                href: 'admin.accounting.reports.index',
                routeName: 'admin.accounting.reports.*',
                permission: 'accounting.view-reports',
                icon: BarChart3,
                keywords: ['trial balance', 'p&l', 'balance sheet', 'ledger'],
            },
            {
                label: 'Accounting Events',
                labelKey: 'accountingEvents',
                href: 'admin.accounting.events.index',
                routeName: 'admin.accounting.events.*',
                permission: 'accounting.view',
                icon: AlertCircle,
                keywords: ['failed', 'retry', 'event', 'posting error'],
            },
            {
                label: 'Credit Notes',
                labelKey: 'creditNotes',
                href: 'admin.accounting.credit-notes.index',
                routeName: 'admin.accounting.credit-notes.*',
                permission: 'accounting.view',
                module: 'credit_notes',
                icon: FileSpreadsheet,
                keywords: ['credit note', 'ar', 'customer refund'],
            },
            {
                label: 'Tax Types',
                labelKey: 'taxTypes',
                href: 'admin.accounting.tax-types.index',
                routeName: 'admin.accounting.tax-types.*',
                permission: 'accounting.manage-tax-settings',
                module: 'tax',
                icon: Scale,
                keywords: ['vat', 'gst', 'tax rate'],
            },
            {
                label: 'Bank Accounts',
                labelKey: 'bankAccounts',
                href: 'admin.accounting.bank-accounts.index',
                routeName: 'admin.accounting.bank-accounts.*',
                permission: 'accounting.manage-bank-accounts',
                module: 'bank_reconciliation',
                icon: Landmark,
                keywords: ['bank', 'gl account'],
            },
            {
                label: 'Bank Reconciliation',
                labelKey: 'bankReconciliation',
                href: 'admin.accounting.reconciliation.index',
                routeName: 'admin.accounting.reconciliation.*',
                permission: 'accounting.reconcile-bank',
                module: 'bank_reconciliation',
                icon: ClipboardList,
                keywords: ['reconcile', 'statement', 'match'],
            },
            {
                label: 'Currencies',
                labelKey: 'currencies',
                href: 'admin.accounting.currencies.index',
                routeName: 'admin.accounting.currencies.*',
                permission: 'accounting.view',
                module: 'multi_currency',
                icon: Coins,
                keywords: ['fx', 'exchange rate', 'multi-currency'],
            },
            {
                label: 'Petty Cash',
                labelKey: 'pettyCash',
                href: 'admin.accounting.petty-cash.index',
                routeName: 'admin.accounting.petty-cash.*',
                permission: 'accounting.manage-petty-cash',
                module: 'petty_cash',
                icon: Wallet,
                keywords: ['petty cash', 'imprest', 'voucher'],
            },
            {
                label: 'Cheques',
                labelKey: 'cheques',
                href: 'admin.accounting.cheques.index',
                routeName: 'admin.accounting.cheques.*',
                permission: 'accounting.manage-cheques',
                module: 'cheques',
                icon: Receipt,
                keywords: ['cheque', 'deposit', 'clearance'],
            },
            {
                label: 'Fixed Assets',
                labelKey: 'fixedAssets',
                href: 'admin.accounting.fixed-assets.index',
                routeName: 'admin.accounting.fixed-assets.*',
                permission: 'accounting.manage-assets',
                module: 'fixed_assets',
                icon: Package,
                keywords: ['asset', 'depreciation', 'capital'],
            },
        ],
    },
    {
        label: 'Admin',
        labelKey: 'admin',
        items: [
            {
                label: 'Users',
                labelKey: 'users',
                href: 'admin.users.index',
                routeName: 'admin.users.*',
                permission: 'users.view',
                icon: Users,
                keywords: ['team', 'staff', 'members'],
            },
            {
                label: 'Roles',
                labelKey: 'roles',
                href: 'admin.roles.index',
                routeName: 'admin.roles.*',
                permission: 'roles.view',
                icon: Shield,
                keywords: ['access', 'profiles'],
            },
            {
                label: 'Permissions',
                labelKey: 'permissions',
                href: 'admin.permissions.index',
                routeName: 'admin.permissions.*',
                permission: 'permissions.view',
                icon: KeyRound,
                keywords: ['capabilities', 'acl'],
            },
            {
                label: 'Settings',
                labelKey: 'settings',
                href: 'admin.settings.index',
                routeName: 'admin.settings.*',
                permission: 'settings.view',
                permissionsAny: [
                    'settings.view',
                    'settings.general.update',
                    'settings.company.update',
                    'settings.notifications.update',
                    'settings.import-export.update',
                ],
                icon: Settings2,
                keywords: ['configuration', 'preferences', 'global'],
            },
        ],
    },
];
