import AdminFormField from '@/Components/common/AdminFormField';

/**
 * Read-only code field for auto-generated HR / document codes.
 */
export default function AutoGeneratedCodeField({
    id = 'code',
    label,
    value = '',
    error,
    hint,
}) {
    return (
        <AdminFormField label={label} id={id} error={error} hint={hint}>
            <input
                id={id}
                value={value ?? ''}
                className="rp-form-input w-full bg-rp-surface-inset"
                readOnly
                disabled
            />
        </AdminFormField>
    );
}
