import AdminFormField from '@/Components/common/AdminFormField';
import AutoGeneratedCodeField from '@/Components/common/AutoGeneratedCodeField';
import ScrollArea from '@/Components/common/ScrollArea';
import DataTable from '@/Components/common/DataTable';
import PageHeader from '@/Components/common/PageHeader';
import Modal from '@/Components/Modal';
import { Button } from '@/Components/ui/button';
import Select from '@/Components/ui/select';
import { withAdminLayout } from '@/HOCs/withAdminLayout';
import { useCan } from '@/Hooks/useCan';
import { Head, router, useForm } from '@inertiajs/react';
import { Layers, Plus, Search, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

function emptyComponentRow() {
    return { pay_component_id: '', amount_or_rate: '', sequence: '' };
}

function emptyForm(legalEntities = [], nextCode = '') {
    return {
        legal_entity_id: legalEntities[0] ? String(legalEntities[0].id) : '',
        code: nextCode ?? '',
        name: '',
        status: 'active',
        components: [],
    };
}

function Index({ structures, filters, legalEntities = [], payComponents = [], nextCode = '' }) {
    const can = useCan();
    const { t } = useTranslation();
    const [modalOpen, setModalOpen] = useState(false);
    const [editing, setEditing] = useState(null);
    const form = useForm(emptyForm(legalEntities, nextCode));

    const statusOptions = useMemo(
        () => [
            { value: '', label: t('pages.salaryStructures.allStatuses') },
            ...['active', 'inactive'].map((status) => ({
                value: status,
                label: t(`pages.salaryStructures.statuses.${status}`),
            })),
        ],
        [t],
    );

    const formStatusOptions = useMemo(
        () =>
            ['active', 'inactive'].map((status) => ({
                value: status,
                label: t(`pages.salaryStructures.statuses.${status}`),
            })),
        [t],
    );

    const entityOptions = useMemo(
        () => [
            { value: '', label: t('pages.salaryStructures.fields.noLegalEntity') },
            ...legalEntities.map((e) => ({ value: String(e.id), label: e.legal_name })),
        ],
        [legalEntities, t],
    );

    const payComponentOptions = useMemo(
        () => [
            { value: '', label: t('pages.salaryStructures.components.noPayComponent') },
            ...payComponents.map((c) => ({ value: String(c.id), label: `${c.code} — ${c.name}` })),
        ],
        [payComponents, t],
    );

    const openCreate = () => {
        setEditing(null);
        form.clearErrors();
        form.setData(emptyForm(legalEntities, nextCode));
        setModalOpen(true);
    };

    const openEdit = (row) => {
        setEditing(row);
        form.clearErrors();
        form.setData({
            legal_entity_id: row.legal_entity_id ? String(row.legal_entity_id) : '',
            code: row.code ?? '',
            name: row.name ?? '',
            status: row.status ?? 'active',
            components: (row.components ?? []).map((c) => ({
                pay_component_id: c.pay_component_id ? String(c.pay_component_id) : '',
                amount_or_rate: c.amount_or_rate ?? '',
                sequence: c.sequence != null ? String(c.sequence) : '',
            })),
        });
        setModalOpen(true);
    };

    const addComponentRow = () => {
        form.setData('components', [...form.data.components, emptyComponentRow()]);
    };

    const removeComponentRow = (index) => {
        form.setData(
            'components',
            form.data.components.filter((_, i) => i !== index),
        );
    };

    const updateComponentRow = (index, patch) => {
        form.setData(
            'components',
            form.data.components.map((row, i) => (i === index ? { ...row, ...patch } : row)),
        );
    };

    const submit = (e) => {
        e.preventDefault();
        const options = {
            preserveScroll: true,
            onSuccess: () => setModalOpen(false),
            onFinish: () => form.transform((data) => data),
        };
        const payload = { ...form.data };
        delete payload.code;

        form.transform(() => payload);

        if (editing) {
            form.put(route('admin.payroll.salary-structures.update', editing.id), options);
        } else {
            form.post(route('admin.payroll.salary-structures.store'), options);
        }
    };

    const search = (e) => {
        e.preventDefault();
        router.get(route('admin.payroll.salary-structures.index'), Object.fromEntries(new FormData(e.target)), {
            preserveState: true,
        });
    };

    const columns = useMemo(
        () => [
            {
                id: 'name',
                header: t('pages.salaryStructures.columns.name'),
                cell: ({ row }) => (
                    <div className="flex items-center gap-3">
                        <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-100 text-violet-600 dark:bg-violet-500/20 dark:text-violet-300">
                            <Layers className="h-4 w-4" />
                        </span>
                        <div>
                            <div className="text-sm font-semibold text-rp-text">{row.original.name}</div>
                            <div className="text-xs text-rp-text-muted">{row.original.code}</div>
                        </div>
                    </div>
                ),
            },
            {
                id: 'legalEntity',
                header: t('pages.salaryStructures.columns.legalEntity'),
                cell: ({ row }) => row.original.legal_entity ?? '—',
            },
            {
                id: 'components',
                header: t('pages.salaryStructures.columns.components'),
                cell: ({ row }) =>
                    row.original.components.length > 0
                        ? row.original.components.map((c) => c.pay_component).join(', ')
                        : '—',
            },
            {
                id: 'status',
                header: t('pages.salaryStructures.columns.status'),
                cell: ({ row }) =>
                    t(`pages.salaryStructures.statuses.${row.original.status}`, {
                        defaultValue: row.original.status,
                    }),
            },
        ],
        [t],
    );

    const rowActions = (row) => {
        if (!can('payroll.manage-structures')) {
            return [];
        }

        return [{ label: t('common.edit'), type: 'edit', onClick: () => openEdit(row) }];
    };

    return (
        <>
            <Head title={t('pages.salaryStructures.indexTitle')} />
            <PageHeader
                title={t('pages.salaryStructures.indexTitle')}
                description={t('pages.salaryStructures.indexDescription')}
            >
                {can('payroll.manage-structures') && (
                    <Button variant="brand" onClick={openCreate}>
                        <Plus className="h-4 w-4" />
                        {t('pages.salaryStructures.createTitle')}
                    </Button>
                )}
            </PageHeader>

            <form onSubmit={search} className="rp-filter-bar mb-4 flex-wrap gap-2">
                <div className="rp-search-inset min-w-[200px] flex-1">
                    <Search className="h-3.5 w-3.5 shrink-0 text-rp-text-muted" />
                    <input
                        name="search"
                        defaultValue={filters.search ?? ''}
                        placeholder={t('pages.salaryStructures.searchPlaceholder')}
                        className="rp-search-input"
                    />
                </div>
                <Select
                    name="status"
                    defaultValue={filters.status ?? ''}
                    className="w-auto min-w-[12rem]"
                    options={statusOptions}
                />
                <Button type="submit" variant="outline">
                    {t('common.search')}
                </Button>
            </form>

            <DataTable
                columns={columns}
                data={structures.data ?? []}
                pagination={structures}
                rowActions={rowActions}
                emptyMessage={t('pages.salaryStructures.empty')}
            />

            <Modal show={modalOpen} onClose={() => setModalOpen(false)} maxWidth="2xl">
                <form onSubmit={submit} className="flex flex-col">
                    <ScrollArea className="max-h-[min(70vh,calc(100dvh-10rem))] space-y-4 overflow-y-auto px-6 py-5">
                        <h3 className="text-lg font-semibold">
                            {editing
                                ? t('pages.salaryStructures.editTitle', { name: editing.name })
                                : t('pages.salaryStructures.createTitle')}
                        </h3>
                        <div className="grid gap-3 sm:grid-cols-2">
                            <AutoGeneratedCodeField
                                label={t('pages.salaryStructures.fields.code')}
                                value={editing ? form.data.code : nextCode}
                                error={form.errors.code}
                                hint={editing ? undefined : t('pages.salaryStructures.fields.codeAutoHint')}
                            />
                            <AdminFormField
                                label={t('pages.salaryStructures.fields.name')}
                                id="name"
                                error={form.errors.name}
                            >
                                <input
                                    id="name"
                                    value={form.data.name}
                                    onChange={(e) => form.setData('name', e.target.value)}
                                    placeholder={t('pages.salaryStructures.fields.namePlaceholder')}
                                    className="rp-form-input"
                                    required
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.salaryStructures.fields.legalEntity')}
                                id="legal_entity_id"
                                error={form.errors.legal_entity_id}
                            >
                                <Select
                                    id="legal_entity_id"
                                    value={form.data.legal_entity_id}
                                    onChange={(value) => form.setData('legal_entity_id', value ?? '')}
                                    options={entityOptions}
                                    isClearable
                                />
                            </AdminFormField>
                            <AdminFormField label={t('common.status')} id="status" error={form.errors.status}>
                                <Select
                                    id="status"
                                    value={form.data.status}
                                    onChange={(value) => form.setData('status', value ?? 'active')}
                                    options={formStatusOptions}
                                />
                            </AdminFormField>
                        </div>

                        <div className="space-y-3 border-t border-rp-border pt-4">
                            <div className="flex items-center justify-between">
                                <h4 className="text-sm font-semibold text-rp-text">
                                    {t('pages.salaryStructures.components.title')}
                                </h4>
                                <Button type="button" variant="outline" size="sm" onClick={addComponentRow}>
                                    <Plus className="h-3.5 w-3.5" />
                                    {t('pages.salaryStructures.components.addLine')}
                                </Button>
                            </div>

                            {form.data.components.map((row, index) => (
                                <div key={index} className="grid gap-2 sm:grid-cols-[1fr_140px_100px_auto] sm:items-end">
                                    <AdminFormField
                                        label={t('pages.salaryStructures.components.payComponent')}
                                        error={form.errors[`components.${index}.pay_component_id`]}
                                    >
                                        <Select
                                            value={row.pay_component_id}
                                            options={payComponentOptions}
                                            onChange={(value) =>
                                                updateComponentRow(index, { pay_component_id: value ?? '' })
                                            }
                                        />
                                    </AdminFormField>
                                    <AdminFormField
                                        label={t('pages.salaryStructures.components.amountOrRate')}
                                        error={form.errors[`components.${index}.amount_or_rate`]}
                                    >
                                        <input
                                            type="number"
                                            min="0"
                                            step="0.01"
                                            className="rp-form-input"
                                            value={row.amount_or_rate}
                                            onChange={(e) =>
                                                updateComponentRow(index, { amount_or_rate: e.target.value })
                                            }
                                        />
                                    </AdminFormField>
                                    <AdminFormField
                                        label={t('pages.salaryStructures.components.sequence')}
                                        error={form.errors[`components.${index}.sequence`]}
                                    >
                                        <input
                                            type="number"
                                            min="0"
                                            className="rp-form-input"
                                            value={row.sequence}
                                            onChange={(e) => updateComponentRow(index, { sequence: e.target.value })}
                                        />
                                    </AdminFormField>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        size="icon"
                                        aria-label={t('pages.salaryStructures.components.remove')}
                                        onClick={() => removeComponentRow(index)}
                                    >
                                        <Trash2 className="h-4 w-4" />
                                    </Button>
                                </div>
                            ))}
                        </div>
                    </ScrollArea>
                    <div className="flex shrink-0 justify-end gap-2 border-t border-rp-border bg-rp-surface px-6 py-4">
                        <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>
                            {t('confirm.cancel')}
                        </Button>
                        <Button type="submit" variant="brand" disabled={form.processing}>
                            {editing ? t('common.save') : t('pages.salaryStructures.createSubmit')}
                        </Button>
                    </div>
                </form>
            </Modal>
        </>
    );
}

export default withAdminLayout(Index);
