<?php

declare(strict_types=1);

namespace App\Providers;

use App\Events\Accounting\CreditNoteIssued;
use App\Events\Procurement\DebitNoteIssued;
use App\Events\Procurement\DropShipGrnConfirmed;
use App\Events\Procurement\GoodsReceived;
use App\Events\Procurement\SupplierInvoiceMatched;
use App\Events\Procurement\SupplierPaymentRecorded;
use App\Events\SaleCompleted;
use App\Listeners\Accounting\PostCreditNoteToAccounting;
use App\Listeners\Accounting\ProcessAccountingOnDebitNoteIssued;
use App\Listeners\Accounting\ProcessAccountingOnGoodsReceived;
use App\Listeners\Accounting\ProcessAccountingOnSaleCompleted;
use App\Listeners\Accounting\ProcessAccountingOnSupplierInvoiceMatched;
use App\Listeners\Accounting\ProcessAccountingOnSupplierPaymentRecorded;
use App\Listeners\ProcessLoyaltyOnSaleCompleted;
use App\Listeners\Procurement\LogDropShipGrnConfirmed;
use App\Listeners\Procurement\LogGoodsReceived;
use App\Listeners\Procurement\LogSupplierInvoiceMatched;
use App\Models\AccountingEvent;
use App\Models\AccountMapping;
use App\Models\AssetCategory;
use App\Models\BankAccount;
use App\Models\Branch;
use App\Models\BranchAccountingProfile;
use App\Models\Brand;
use App\Models\Category;
use App\Models\ChartOfAccount;
use App\Models\Cheque;
use App\Models\CostCentre;
use App\Models\CreditNote;
use App\Models\Currency;
use App\Models\Customer;
use App\Models\DebitNote;
use App\Models\ExchangeRate;
use App\Models\FiscalYear;
use App\Models\FixedAsset;
use App\Models\GoodsReceivingNote;
use App\Models\JournalEntry;
use App\Models\LandedCostEntry;
use App\Models\LoyaltyApprovalPolicy;
use App\Models\LoyaltyCampaign;
use App\Models\LoyaltyExpiryRule;
use App\Models\LoyaltyProgram;
use App\Models\LoyaltyProgramTier;
use App\Models\LoyaltyRule;
use App\Models\Permission;
use App\Models\PettyCashRegister;
use App\Models\PettyCashVoucher;
use App\Models\PoMatchResult;
use App\Models\PostingRuleSet;
use App\Models\Product;
use App\Models\PurchaseOrder;
use App\Models\PurchaseReturn;
use App\Models\Role;
use App\Models\Sale;
use App\Models\SaleInvoice;
use App\Models\SalePayment;
use App\Models\Supplier;
use App\Models\SupplierAttachment;
use App\Models\SupplierInvoice;
use App\Models\SupplierPayment;
use App\Models\SupplierPriceList;
use App\Models\SupplierPriceListItem;
use App\Models\TaxType;
use App\Models\Unit;
use App\Models\User;
use App\Models\Warehouse;
use App\Observers\AuditObserver;
use App\Repositories\Contracts\AccountingEventRepositoryInterface;
use App\Repositories\Contracts\AccountMappingRepositoryInterface;
use App\Repositories\Contracts\BankAccountRepositoryInterface;
use App\Repositories\Contracts\BinLocationRepositoryInterface;
use App\Repositories\Contracts\BranchRepositoryInterface;
use App\Repositories\Contracts\BrandRepositoryInterface;
use App\Repositories\Contracts\CategoryRepositoryInterface;
use App\Repositories\Contracts\ChartOfAccountRepositoryInterface;
use App\Repositories\Contracts\ChequeRepositoryInterface;
use App\Repositories\Contracts\CostCentreRepositoryInterface;
use App\Repositories\Contracts\CountSessionRepositoryInterface;
use App\Repositories\Contracts\CreditNoteRepositoryInterface;
use App\Repositories\Contracts\CurrencyRepositoryInterface;
use App\Repositories\Contracts\CustomerRepositoryInterface;
use App\Repositories\Contracts\FiscalYearRepositoryInterface;
use App\Repositories\Contracts\FixedAssetRepositoryInterface;
use App\Repositories\Contracts\IdentifierSequenceRepositoryInterface;
use App\Repositories\Contracts\ImageRepositoryInterface;
use App\Repositories\Contracts\InventoryRepositoryInterface;
use App\Repositories\Contracts\JournalEntryRepositoryInterface;
use App\Repositories\Contracts\PermissionRepositoryInterface;
use App\Repositories\Contracts\PettyCashRegisterRepositoryInterface;
use App\Repositories\Contracts\PosCartRepositoryInterface;
use App\Repositories\Contracts\PostingRuleSetRepositoryInterface;
use App\Repositories\Contracts\ProductRepositoryInterface;
use App\Repositories\Contracts\PurchaseOrderRepositoryInterface;
use App\Repositories\Contracts\RoleRepositoryInterface;
use App\Repositories\Contracts\StockMovementRepositoryInterface;
use App\Repositories\Contracts\StockTransferRepositoryInterface;
use App\Repositories\Contracts\SupplierRepositoryInterface;
use App\Repositories\Contracts\SystemSettingRepositoryInterface;
use App\Repositories\Contracts\TaxTypeRepositoryInterface;
use App\Repositories\Contracts\UnitRepositoryInterface;
use App\Repositories\Contracts\UserRepositoryInterface;
use App\Repositories\Contracts\WarehouseRepositoryInterface;
use App\Repositories\Eloquent\AccountingEventRepository;
use App\Repositories\Eloquent\AccountMappingRepository;
use App\Repositories\Eloquent\BankAccountRepository;
use App\Repositories\Eloquent\BinLocationRepository;
use App\Repositories\Eloquent\BranchRepository;
use App\Repositories\Eloquent\BrandRepository;
use App\Repositories\Eloquent\CategoryRepository;
use App\Repositories\Eloquent\ChartOfAccountRepository;
use App\Repositories\Eloquent\ChequeRepository;
use App\Repositories\Eloquent\CostCentreRepository;
use App\Repositories\Eloquent\CountSessionRepository;
use App\Repositories\Eloquent\CreditNoteRepository;
use App\Repositories\Eloquent\CurrencyRepository;
use App\Repositories\Eloquent\CustomerRepository;
use App\Repositories\Eloquent\FiscalYearRepository;
use App\Repositories\Eloquent\FixedAssetRepository;
use App\Repositories\Eloquent\IdentifierSequenceRepository;
use App\Repositories\Eloquent\ImageRepository;
use App\Repositories\Eloquent\InventoryRepository;
use App\Repositories\Eloquent\JournalEntryRepository;
use App\Repositories\Eloquent\PermissionRepository;
use App\Repositories\Eloquent\PettyCashRegisterRepository;
use App\Repositories\Eloquent\PosCartRepository;
use App\Repositories\Eloquent\PostingRuleSetRepository;
use App\Repositories\Eloquent\ProductRepository;
use App\Repositories\Eloquent\PurchaseOrderRepository;
use App\Repositories\Eloquent\RoleRepository;
use App\Repositories\Eloquent\StockMovementRepository;
use App\Repositories\Eloquent\StockTransferRepository;
use App\Repositories\Eloquent\SupplierRepository;
use App\Repositories\Eloquent\SystemSettingRepository;
use App\Repositories\Eloquent\TaxTypeRepository;
use App\Repositories\Eloquent\UnitRepository;
use App\Repositories\Eloquent\UserRepository;
use App\Repositories\Eloquent\WarehouseRepository;
use App\Services\Accounting\ProcurementAccountingHook;
use App\Services\Procurement\Contracts\ProcurementPostingHook;
use Illuminate\Cache\RateLimiting\Limit;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\RateLimiter;
use Illuminate\Support\Facades\Vite;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->bind(AccountingEventRepositoryInterface::class, AccountingEventRepository::class);
        $this->app->bind(AccountMappingRepositoryInterface::class, AccountMappingRepository::class);
        $this->app->bind(BankAccountRepositoryInterface::class, BankAccountRepository::class);
        $this->app->bind(PosCartRepositoryInterface::class, PosCartRepository::class);
        $this->app->bind(UserRepositoryInterface::class, UserRepository::class);
        $this->app->bind(RoleRepositoryInterface::class, RoleRepository::class);
        $this->app->bind(PermissionRepositoryInterface::class, PermissionRepository::class);
        $this->app->bind(BranchRepositoryInterface::class, BranchRepository::class);
        $this->app->bind(WarehouseRepositoryInterface::class, WarehouseRepository::class);
        $this->app->bind(CategoryRepositoryInterface::class, CategoryRepository::class);
        $this->app->bind(ChartOfAccountRepositoryInterface::class, ChartOfAccountRepository::class);
        $this->app->bind(BrandRepositoryInterface::class, BrandRepository::class);
        $this->app->bind(CustomerRepositoryInterface::class, CustomerRepository::class);
        $this->app->bind(TaxTypeRepositoryInterface::class, TaxTypeRepository::class);
        $this->app->bind(UnitRepositoryInterface::class, UnitRepository::class);
        $this->app->bind(SupplierRepositoryInterface::class, SupplierRepository::class);
        $this->app->bind(PurchaseOrderRepositoryInterface::class, PurchaseOrderRepository::class);
        $this->app->bind(PettyCashRegisterRepositoryInterface::class, PettyCashRegisterRepository::class);
        $this->app->bind(PostingRuleSetRepositoryInterface::class, PostingRuleSetRepository::class);
        $this->app->bind(ProductRepositoryInterface::class, ProductRepository::class);
        $this->app->bind(ImageRepositoryInterface::class, ImageRepository::class);
        $this->app->bind(FiscalYearRepositoryInterface::class, FiscalYearRepository::class);
        $this->app->bind(FixedAssetRepositoryInterface::class, FixedAssetRepository::class);
        $this->app->bind(IdentifierSequenceRepositoryInterface::class, IdentifierSequenceRepository::class);
        $this->app->bind(InventoryRepositoryInterface::class, InventoryRepository::class);
        $this->app->bind(JournalEntryRepositoryInterface::class, JournalEntryRepository::class);
        $this->app->bind(BinLocationRepositoryInterface::class, BinLocationRepository::class);
        $this->app->bind(ChequeRepositoryInterface::class, ChequeRepository::class);
        $this->app->bind(CostCentreRepositoryInterface::class, CostCentreRepository::class);
        $this->app->bind(CountSessionRepositoryInterface::class, CountSessionRepository::class);
        $this->app->bind(CreditNoteRepositoryInterface::class, CreditNoteRepository::class);
        $this->app->bind(CurrencyRepositoryInterface::class, CurrencyRepository::class);
        $this->app->bind(StockMovementRepositoryInterface::class, StockMovementRepository::class);
        $this->app->bind(StockTransferRepositoryInterface::class, StockTransferRepository::class);
        $this->app->bind(SystemSettingRepositoryInterface::class, SystemSettingRepository::class);
        $this->app->singleton(ProcurementPostingHook::class, ProcurementAccountingHook::class);
    }

    public function boot(): void
    {
        Vite::prefetch(concurrency: 3);

        User::observe(AuditObserver::class);
        Role::observe(AuditObserver::class);
        Permission::observe(AuditObserver::class);
        Branch::observe(AuditObserver::class);
        Warehouse::observe(AuditObserver::class);
        Category::observe(AuditObserver::class);
        Brand::observe(AuditObserver::class);
        Unit::observe(AuditObserver::class);
        Product::observe(AuditObserver::class);
        Customer::observe(AuditObserver::class);
        Supplier::observe(AuditObserver::class);
        PurchaseOrder::observe(AuditObserver::class);
        GoodsReceivingNote::observe(AuditObserver::class);
        SupplierInvoice::observe(AuditObserver::class);
        SupplierPayment::observe(AuditObserver::class);
        PurchaseReturn::observe(AuditObserver::class);
        SupplierPriceList::observe(AuditObserver::class);
        SupplierPriceListItem::observe(AuditObserver::class);
        SupplierAttachment::observe(AuditObserver::class);
        LandedCostEntry::observe(AuditObserver::class);
        PoMatchResult::observe(AuditObserver::class);
        DebitNote::observe(AuditObserver::class);
        Sale::observe(AuditObserver::class);
        SalePayment::observe(AuditObserver::class);
        SaleInvoice::observe(AuditObserver::class);
        LoyaltyProgram::observe(AuditObserver::class);
        LoyaltyRule::observe(AuditObserver::class);
        LoyaltyProgramTier::observe(AuditObserver::class);
        LoyaltyApprovalPolicy::observe(AuditObserver::class);
        LoyaltyExpiryRule::observe(AuditObserver::class);
        LoyaltyCampaign::observe(AuditObserver::class);
        ChartOfAccount::observe(AuditObserver::class);
        AccountMapping::observe(AuditObserver::class);
        PostingRuleSet::observe(AuditObserver::class);
        JournalEntry::observe(AuditObserver::class);
        FiscalYear::observe(AuditObserver::class);
        AccountingEvent::observe(AuditObserver::class);
        CostCentre::observe(AuditObserver::class);
        TaxType::observe(AuditObserver::class);
        CreditNote::observe(AuditObserver::class);
        Currency::observe(AuditObserver::class);
        ExchangeRate::observe(AuditObserver::class);
        BankAccount::observe(AuditObserver::class);
        BranchAccountingProfile::observe(AuditObserver::class);
        AssetCategory::observe(AuditObserver::class);
        FixedAsset::observe(AuditObserver::class);
        PettyCashRegister::observe(AuditObserver::class);
        PettyCashVoucher::observe(AuditObserver::class);
        Cheque::observe(AuditObserver::class);

        RateLimiter::for('login', function (Request $request) {
            $email = (string) $request->input('email');

            return Limit::perMinute(5)->by(strtolower($email).'|'.$request->ip());
        });

        Event::listen(DropShipGrnConfirmed::class, LogDropShipGrnConfirmed::class);
        Event::listen(GoodsReceived::class, LogGoodsReceived::class);
        Event::listen(GoodsReceived::class, ProcessAccountingOnGoodsReceived::class);
        Event::listen(SupplierInvoiceMatched::class, LogSupplierInvoiceMatched::class);
        Event::listen(SupplierInvoiceMatched::class, ProcessAccountingOnSupplierInvoiceMatched::class);
        Event::listen(SupplierPaymentRecorded::class, ProcessAccountingOnSupplierPaymentRecorded::class);
        Event::listen(DebitNoteIssued::class, ProcessAccountingOnDebitNoteIssued::class);
        Event::listen(SaleCompleted::class, ProcessLoyaltyOnSaleCompleted::class);
        Event::listen(SaleCompleted::class, ProcessAccountingOnSaleCompleted::class);
        Event::listen(CreditNoteIssued::class, PostCreditNoteToAccounting::class);
    }
}
