import AdminFormField from '@/Components/common/AdminFormField';
import AutoGeneratedCodeField from '@/Components/common/AutoGeneratedCodeField';
import DataTable from '@/Components/common/DataTable';
import PageHeader from '@/Components/common/PageHeader';
import ImportExportToolbar from '@/Components/import-export/ImportExportToolbar';
import { useImportJobsTray } from '@/Components/import-export/ImportJobsTray';
import ScrollArea from '@/Components/common/ScrollArea';
import Modal from '@/Components/Modal';
import { Button } from '@/Components/ui/button';
import Select from '@/Components/ui/select';
import { withAdminLayout } from '@/HOCs/withAdminLayout';
import { useCan } from '@/Hooks/useCan';
import { Head, router, useForm } from '@inertiajs/react';
import { Layers, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

function emptyForm(legalEntities = [], nextCode = '', currencies = []) {
    return {
        legal_entity_id: legalEntities[0] ? String(legalEntities[0].id) : '',
        code: nextCode ?? '',
        name: '',
        rank: '0',
        currency_code: currencies[0]?.code ?? '',
        min_amount: '',
        mid_amount: '',
        max_amount: '',
        enforce_salary_band: false,
        effective_from: '',
        effective_to: '',
        status: 'active',
    };
}

function Index({ grades, filters, legalEntities = [], currencies = [], nextCode = '' }) {
    const can = useCan();
    const { t } = useTranslation();
    const { trackJob } = useImportJobsTray();
    const [modalOpen, setModalOpen] = useState(false);
    const [editing, setEditing] = useState(null);
    const form = useForm(emptyForm(legalEntities, nextCode, currencies));

    const statusOptions = useMemo(
        () => [
            { value: '', label: t('common.allStatuses') },
            { value: 'active', label: t('pages.hrGrades.statuses.active') },
            { value: 'inactive', label: t('pages.hrGrades.statuses.inactive') },
        ],
        [t],
    );

    const entityOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrEmployees.selectLegalEntity') },
            ...legalEntities.map((e) => ({ value: String(e.id), label: e.legal_name })),
        ],
        [legalEntities, t],
    );

    const formStatusOptions = useMemo(
        () => [
            { value: 'active', label: t('pages.hrGrades.statuses.active') },
            { value: 'inactive', label: t('pages.hrGrades.statuses.inactive') },
        ],
        [t],
    );

    const currencyOptions = useMemo(
        () => [
            { value: '', label: t('common.selectCurrency') },
            ...currencies.map((c) => ({ value: c.code, label: `${c.code} — ${c.name}` })),
        ],
        [currencies, t],
    );

    const openCreate = () => {
        setEditing(null);
        form.clearErrors();
        form.setData(emptyForm(legalEntities, nextCode, currencies));
        setModalOpen(true);
    };

    const openEdit = (row) => {
        setEditing(row);
        form.clearErrors();
        form.setData({
            legal_entity_id: row.legal_entity_id ? String(row.legal_entity_id) : '',
            code: row.code ?? '',
            name: row.name ?? '',
            rank: row.rank != null ? String(row.rank) : '0',
            currency_code: row.currency_code ?? '',
            min_amount: row.min_amount != null ? String(row.min_amount) : '',
            mid_amount: row.mid_amount != null ? String(row.mid_amount) : '',
            max_amount: row.max_amount != null ? String(row.max_amount) : '',
            enforce_salary_band: !!row.enforce_salary_band,
            effective_from: row.effective_from ?? '',
            effective_to: row.effective_to ?? '',
            status: row.status ?? 'active',
        });
        setModalOpen(true);
    };

    const submit = (e) => {
        e.preventDefault();
        const options = {
            preserveScroll: true,
            onSuccess: () => setModalOpen(false),
            onFinish: () => form.transform((data) => data),
        };
        const payload = { ...form.data };
        delete payload.code;

        form.transform(() => payload);

        if (editing) {
            form.put(route('admin.hr.grades.update', editing.id), options);
        } else {
            form.post(route('admin.hr.grades.store'), options);
        }
    };

    const search = (e) => {
        e.preventDefault();
        router.get(route('admin.hr.grades.index'), Object.fromEntries(new FormData(e.target)), {
            preserveState: true,
        });
    };

    const columns = useMemo(
        () => [
            {
                id: 'name',
                header: t('pages.hrGrades.columns.name'),
                cell: ({ row }) => (
                    <div className="flex items-center gap-3">
                        <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-violet-100 text-violet-600 dark:bg-violet-500/20 dark:text-violet-300">
                            <Layers className="h-4 w-4" />
                        </span>
                        <div>
                            <div className="text-sm font-semibold text-rp-text">{row.original.name}</div>
                            <div className="text-xs text-rp-text-muted">{row.original.code}</div>
                        </div>
                    </div>
                ),
            },
            {
                id: 'rank',
                header: t('pages.hrGrades.columns.rank'),
                cell: ({ row }) => row.original.rank ?? '—',
            },
            {
                id: 'band',
                header: t('pages.hrGrades.columns.salaryBand'),
                cell: ({ row }) =>
                    row.original.min_amount != null
                        ? `${row.original.min_amount} – ${row.original.max_amount ?? '∞'}`
                        : '—',
            },
            {
                id: 'status',
                header: t('pages.hrGrades.columns.status'),
                cell: ({ row }) =>
                    t(`pages.hrGrades.statuses.${row.original.status}`, {
                        defaultValue: row.original.status,
                    }),
            },
        ],
        [t],
    );

    const rowActions = (row) => {
        if (!can('hr.manage-org')) {
            return [];
        }

        return [{ label: t('common.edit'), type: 'edit', onClick: () => openEdit(row) }];
    };

    return (
        <>
            <Head title={t('pages.hrGrades.indexTitle')} />
            <PageHeader
                title={t('pages.hrGrades.indexTitle')}
                description={t('pages.hrGrades.indexDescription')}
            >
                <div className="flex flex-wrap items-center gap-2">
                    <ImportExportToolbar
                        entityType="grades"
                        entityLabel={t('pages.hrGrades.indexTitle')}
                        exportOptions={{ filters: { search: filters.search ?? undefined, status: filters.status ?? undefined } }}
                        onJobStarted={trackJob}
                    />
                    {can('hr.manage-org') && (
                        <Button variant="brand" onClick={openCreate}>
                            <Plus className="h-4 w-4" />
                            {t('pages.hrGrades.createTitle')}
                        </Button>
                    )}
                </div>
            </PageHeader>

            <form onSubmit={search} className="rp-filter-bar mb-4 flex-wrap gap-2">
                <div className="rp-search-inset min-w-[200px] flex-1">
                    <Search className="h-3.5 w-3.5 shrink-0 text-rp-text-muted" />
                    <input
                        name="search"
                        defaultValue={filters.search ?? ''}
                        placeholder={t('pages.hrGrades.searchPlaceholder')}
                        className="rp-search-input"
                    />
                </div>
                <Select
                    name="status"
                    defaultValue={filters.status ?? ''}
                    className="w-auto min-w-[12rem]"
                    options={statusOptions}
                />
                <Button type="submit" variant="outline">
                    {t('common.search')}
                </Button>
            </form>

            <DataTable
                columns={columns}
                data={grades.data ?? []}
                pagination={grades}
                rowActions={rowActions}
                emptyMessage={t('pages.hrGrades.empty')}
            />

            <Modal show={modalOpen} onClose={() => setModalOpen(false)} maxWidth="2xl">
                <form onSubmit={submit} className="flex flex-col">
                    <ScrollArea className="max-h-[min(70vh,calc(100dvh-10rem))] space-y-4 overflow-y-auto px-6 py-5">
                        <h3 className="text-lg font-semibold">
                            {editing
                                ? t('pages.hrGrades.editTitle', { name: editing.name })
                                : t('pages.hrGrades.createTitle')}
                        </h3>
                        <div className="grid gap-3 sm:grid-cols-2">
                            <AdminFormField
                                label={t('pages.hrEmployees.fields.legalEntity')}
                                id="legal_entity_id"
                                error={form.errors.legal_entity_id}
                            >
                                <Select
                                    id="legal_entity_id"
                                    value={form.data.legal_entity_id}
                                    onChange={(value) => form.setData('legal_entity_id', value ?? '')}
                                    options={entityOptions}
                                />
                            </AdminFormField>
                            <AutoGeneratedCodeField
                                label={t('pages.hrGrades.fields.code')}
                                value={editing ? form.data.code : nextCode}
                                error={form.errors.code}
                                hint={editing ? undefined : t('pages.hrGrades.fields.codeAutoHint')}
                            />
                            <AdminFormField label={t('pages.hrGrades.fields.name')} id="name" error={form.errors.name}>
                                <input
                                    id="name"
                                    value={form.data.name}
                                    onChange={(e) => form.setData('name', e.target.value)}
                                    placeholder={t('pages.hrGrades.fields.namePlaceholder')}
                                    className="rp-form-input"
                                    required
                                />
                            </AdminFormField>
                            <AdminFormField label={t('pages.hrGrades.fields.rank')} id="rank" error={form.errors.rank}>
                                <input
                                    id="rank"
                                    type="number"
                                    min="0"
                                    value={form.data.rank}
                                    onChange={(e) => form.setData('rank', e.target.value)}
                                    placeholder={t('pages.hrGrades.fields.rankPlaceholder')}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.currency')}
                                id="currency_code"
                                error={form.errors.currency_code}
                            >
                                <Select
                                    id="currency_code"
                                    value={form.data.currency_code}
                                    onChange={(value) => form.setData('currency_code', value ?? '')}
                                    options={currencyOptions}
                                    isClearable
                                    placeholder={t('common.selectCurrency')}
                                />
                            </AdminFormField>
                            <AdminFormField label={t('common.status')} id="status" error={form.errors.status}>
                                <Select
                                    id="status"
                                    value={form.data.status}
                                    onChange={(value) => form.setData('status', value ?? 'active')}
                                    options={formStatusOptions}
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.minAmount')}
                                id="min_amount"
                                error={form.errors.min_amount}
                            >
                                <input
                                    id="min_amount"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={form.data.min_amount}
                                    onChange={(e) => form.setData('min_amount', e.target.value)}
                                    placeholder={t('pages.hrGrades.fields.amountPlaceholder')}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.midAmount')}
                                id="mid_amount"
                                error={form.errors.mid_amount}
                            >
                                <input
                                    id="mid_amount"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={form.data.mid_amount}
                                    onChange={(e) => form.setData('mid_amount', e.target.value)}
                                    placeholder={t('pages.hrGrades.fields.amountPlaceholder')}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.maxAmount')}
                                id="max_amount"
                                error={form.errors.max_amount}
                            >
                                <input
                                    id="max_amount"
                                    type="number"
                                    min="0"
                                    step="0.01"
                                    value={form.data.max_amount}
                                    onChange={(e) => form.setData('max_amount', e.target.value)}
                                    placeholder={t('pages.hrGrades.fields.amountPlaceholder')}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.effectiveFrom')}
                                id="effective_from"
                                error={form.errors.effective_from}
                            >
                                <input
                                    id="effective_from"
                                    type="date"
                                    value={form.data.effective_from}
                                    onChange={(e) => form.setData('effective_from', e.target.value)}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <AdminFormField
                                label={t('pages.hrGrades.fields.effectiveTo')}
                                id="effective_to"
                                error={form.errors.effective_to}
                            >
                                <input
                                    id="effective_to"
                                    type="date"
                                    value={form.data.effective_to}
                                    onChange={(e) => form.setData('effective_to', e.target.value)}
                                    className="rp-form-input"
                                />
                            </AdminFormField>
                            <div className="flex items-center gap-2 sm:col-span-2">
                                <input
                                    id="enforce_salary_band"
                                    type="checkbox"
                                    checked={!!form.data.enforce_salary_band}
                                    onChange={(e) => form.setData('enforce_salary_band', e.target.checked)}
                                    className="h-4 w-4 rounded border-rp-border"
                                />
                                <label htmlFor="enforce_salary_band" className="text-sm text-rp-text">
                                    {t('pages.hrGrades.fields.enforceSalaryBand')}
                                </label>
                            </div>
                        </div>
                    </ScrollArea>
                    <div className="flex shrink-0 justify-end gap-2 border-t border-rp-border bg-rp-surface px-6 py-4">
                        <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>
                            {t('confirm.cancel')}
                        </Button>
                        <Button type="submit" variant="brand" disabled={form.processing}>
                            {editing ? t('common.save') : t('pages.hrGrades.createSubmit')}
                        </Button>
                    </div>
                </form>
            </Modal>
        </>
    );
}

export default withAdminLayout(Index);
