import AdminFormField from '@/Components/common/AdminFormField';
import AutoGeneratedCodeField from '@/Components/common/AutoGeneratedCodeField';
import DataTable from '@/Components/common/DataTable';
import PageHeader from '@/Components/common/PageHeader';
import Modal from '@/Components/Modal';
import { Button } from '@/Components/ui/button';
import Select from '@/Components/ui/select';
import { withAdminLayout } from '@/HOCs/withAdminLayout';
import { useCan } from '@/Hooks/useCan';
import { Head, router, useForm } from '@inertiajs/react';
import { Building2, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

function emptyForm(legalEntities = [], nextCode = '') {
    return {
        legal_entity_id: legalEntities[0] ? String(legalEntities[0].id) : '',
        code: nextCode ?? '',
        name: '',
        parent_id: '',
        cost_centre_id: '',
        status: 'active',
    };
}

function Index({ departments, filters, legalEntities = [], parentOptions = [], costCentres = [], nextCode = '' }) {
    const can = useCan();
    const { t } = useTranslation();
    const [modalOpen, setModalOpen] = useState(false);
    const [editing, setEditing] = useState(null);
    const form = useForm(emptyForm(legalEntities, nextCode));

    const statusOptions = useMemo(
        () => [
            { value: '', label: t('common.allStatuses') },
            { value: 'active', label: t('pages.hrDepartments.statuses.active') },
            { value: 'inactive', label: t('pages.hrDepartments.statuses.inactive') },
        ],
        [t],
    );

    const entityOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrEmployees.selectLegalEntity') },
            ...legalEntities.map((e) => ({ value: String(e.id), label: e.legal_name })),
        ],
        [legalEntities, t],
    );

    const parentSelectOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrDepartments.fields.noParent') },
            ...parentOptions
                .filter((p) => !editing || p.id !== editing.id)
                .map((p) => ({ value: String(p.id), label: `${p.code} — ${p.name}` })),
        ],
        [editing, parentOptions, t],
    );

    const costCentreOptions = useMemo(
        () => [
            { value: '', label: t('pages.hrDepartments.fields.noCostCentre') },
            ...costCentres.map((c) => ({ value: String(c.id), label: `${c.code} — ${c.name}` })),
        ],
        [costCentres, t],
    );

    const formStatusOptions = useMemo(
        () => [
            { value: 'active', label: t('pages.hrDepartments.statuses.active') },
            { value: 'inactive', label: t('pages.hrDepartments.statuses.inactive') },
        ],
        [t],
    );

    const openCreate = () => {
        setEditing(null);
        form.clearErrors();
        form.setData(emptyForm(legalEntities, nextCode));
        setModalOpen(true);
    };

    const openEdit = (row) => {
        setEditing(row);
        form.clearErrors();
        form.setData({
            legal_entity_id: row.legal_entity_id ? String(row.legal_entity_id) : '',
            code: row.code ?? '',
            name: row.name ?? '',
            parent_id: row.parent_id ? String(row.parent_id) : '',
            cost_centre_id: row.cost_centre_id ? String(row.cost_centre_id) : '',
            status: row.status ?? 'active',
        });
        setModalOpen(true);
    };

    const submit = (e) => {
        e.preventDefault();
        const options = {
            preserveScroll: true,
            onSuccess: () => setModalOpen(false),
            onFinish: () => form.transform((data) => data),
        };
        const payload = { ...form.data };
        delete payload.code;

        form.transform(() => payload);

        if (editing) {
            form.put(route('admin.hr.departments.update', editing.id), options);
        } else {
            form.post(route('admin.hr.departments.store'), options);
        }
    };

    const search = (e) => {
        e.preventDefault();
        router.get(route('admin.hr.departments.index'), Object.fromEntries(new FormData(e.target)), {
            preserveState: true,
        });
    };

    const columns = useMemo(
        () => [
            {
                id: 'name',
                header: t('pages.hrDepartments.columns.name'),
                cell: ({ row }) => (
                    <div className="flex items-center gap-3">
                        <span className="flex h-9 w-9 items-center justify-center rounded-lg bg-indigo-100 text-indigo-600 dark:bg-indigo-500/20 dark:text-indigo-300">
                            <Building2 className="h-4 w-4" />
                        </span>
                        <div>
                            <div className="text-sm font-semibold text-rp-text">{row.original.name}</div>
                            <div className="text-xs text-rp-text-muted">{row.original.code}</div>
                        </div>
                    </div>
                ),
            },
            {
                id: 'entity',
                header: t('pages.hrDepartments.columns.legalEntity'),
                cell: ({ row }) => row.original.legal_entity_name ?? '—',
            },
            {
                id: 'parent',
                header: t('pages.hrDepartments.columns.parent'),
                cell: ({ row }) => row.original.parent_name ?? '—',
            },
            {
                id: 'status',
                header: t('pages.hrDepartments.columns.status'),
                cell: ({ row }) =>
                    t(`pages.hrDepartments.statuses.${row.original.status}`, {
                        defaultValue: row.original.status,
                    }),
            },
        ],
        [t],
    );

    const rowActions = (row) => {
        if (!can('hr.manage-org')) {
            return [];
        }

        return [{ label: t('common.edit'), type: 'edit', onClick: () => openEdit(row) }];
    };

    return (
        <>
            <Head title={t('pages.hrDepartments.indexTitle')} />
            <PageHeader
                title={t('pages.hrDepartments.indexTitle')}
                description={t('pages.hrDepartments.indexDescription')}
            >
                {can('hr.manage-org') && (
                    <Button variant="brand" onClick={openCreate}>
                        <Plus className="h-4 w-4" />
                        {t('pages.hrDepartments.createTitle')}
                    </Button>
                )}
            </PageHeader>

            <form onSubmit={search} className="rp-filter-bar mb-4 flex-wrap gap-2">
                <div className="rp-search-inset min-w-[200px] flex-1">
                    <Search className="h-3.5 w-3.5 shrink-0 text-rp-text-muted" />
                    <input
                        name="search"
                        defaultValue={filters.search ?? ''}
                        placeholder={t('pages.hrDepartments.searchPlaceholder')}
                        className="rp-search-input"
                    />
                </div>
                <Select
                    name="status"
                    defaultValue={filters.status ?? ''}
                    className="w-auto min-w-[12rem]"
                    options={statusOptions}
                />
                <Button type="submit" variant="outline">
                    {t('common.search')}
                </Button>
            </form>

            <DataTable
                columns={columns}
                data={departments.data ?? []}
                pagination={departments}
                rowActions={rowActions}
                emptyMessage={t('pages.hrDepartments.empty')}
            />

            <Modal show={modalOpen} onClose={() => setModalOpen(false)} maxWidth="lg">
                <form onSubmit={submit} className="space-y-4 p-6">
                    <h3 className="text-lg font-semibold">
                        {editing
                            ? t('pages.hrDepartments.editTitle', { name: editing.name })
                            : t('pages.hrDepartments.createTitle')}
                    </h3>
                    <div className="grid gap-4 sm:grid-cols-2">
                        <AdminFormField
                            label={t('pages.hrEmployees.fields.legalEntity')}
                            id="legal_entity_id"
                            error={form.errors.legal_entity_id}
                        >
                            <Select
                                id="legal_entity_id"
                                value={form.data.legal_entity_id}
                                onChange={(value) => form.setData('legal_entity_id', value ?? '')}
                                options={entityOptions}
                            />
                        </AdminFormField>
                        <AutoGeneratedCodeField
                            label={t('pages.hrDepartments.fields.code')}
                            value={editing ? form.data.code : nextCode}
                            error={form.errors.code}
                            hint={editing ? undefined : t('pages.hrDepartments.fields.codeAutoHint')}
                        />
                        <AdminFormField label={t('pages.hrDepartments.fields.name')} id="name" error={form.errors.name}>
                            <input
                                id="name"
                                value={form.data.name}
                                onChange={(e) => form.setData('name', e.target.value)}
                                className="rp-form-input"
                                required
                            />
                        </AdminFormField>
                        <AdminFormField
                            label={t('pages.hrDepartments.fields.parent')}
                            id="parent_id"
                            error={form.errors.parent_id}
                        >
                            <Select
                                id="parent_id"
                                value={form.data.parent_id}
                                onChange={(value) => form.setData('parent_id', value ?? '')}
                                options={parentSelectOptions}
                                isClearable
                            />
                        </AdminFormField>
                        <AdminFormField
                            label={t('pages.hrDepartments.fields.costCentre')}
                            id="cost_centre_id"
                            error={form.errors.cost_centre_id}
                        >
                            <Select
                                id="cost_centre_id"
                                value={form.data.cost_centre_id}
                                onChange={(value) => form.setData('cost_centre_id', value ?? '')}
                                options={costCentreOptions}
                                isClearable
                            />
                        </AdminFormField>
                        <AdminFormField label={t('common.status')} id="status" error={form.errors.status}>
                            <Select
                                id="status"
                                value={form.data.status}
                                onChange={(value) => form.setData('status', value ?? 'active')}
                                options={formStatusOptions}
                            />
                        </AdminFormField>
                    </div>
                    <div className="flex justify-end gap-2 pt-2">
                        <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>
                            {t('confirm.cancel')}
                        </Button>
                        <Button type="submit" variant="brand" disabled={form.processing}>
                            {editing ? t('common.save') : t('pages.hrDepartments.createSubmit')}
                        </Button>
                    </div>
                </form>
            </Modal>
        </>
    );
}

export default withAdminLayout(Index);
